import type { AiUsageRecord, AiUsageScope, AiUsageStore } from "@micirql/ai";

function config(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY??process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw new Error("Server credit configuration is missing.");return{url,key};}
function headers(){const{key}=config();return{apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json"};}

export function creditsForTask(task:"plan-site"|"generate-image"|"build-component"){const raw=task==="generate-image"?process.env.MICIRQL_CREDITS_GENERATE_IMAGE:task==="build-component"?process.env.MICIRQL_CREDITS_BUILD_COMPONENT:process.env.MICIRQL_CREDITS_PLAN_SITE;const fallback=task==="generate-image"?20:task==="build-component"?8:10;const value=Number(raw??fallback);if(!Number.isInteger(value)||value<=0)throw new Error(`Invalid credit price for ${task}.`);return value;}
export function creditsForWebsiteGeneration(){const value=Number(process.env.MICIRQL_CREDITS_GENERATE_WEBSITE??40);if(!Number.isInteger(value)||value<=0)throw new Error("MICIRQL_CREDITS_GENERATE_WEBSITE must be a positive integer.");return value;}
export function trialCreditAmount(){const value=Number(process.env.MICIRQL_TRIAL_CREDITS??60);if(!Number.isInteger(value)||value<=0)throw new Error("MICIRQL_TRIAL_CREDITS must be a positive integer.");return value;}

export async function grantTrialCredits(workspaceId:string){return rpcBalance("grant_trial_credits",{p_workspace_id:workspaceId,p_credits:trialCreditAmount()});}
export async function reserveCredits(args:{workspaceId:string;credits:number;operationKey:string;description:string;metadata?:Record<string,unknown>}){return rpcBalance("reserve_workspace_credits",{p_workspace_id:args.workspaceId,p_credits:args.credits,p_operation_key:args.operationKey,p_description:args.description,p_metadata:args.metadata??{}});}
export async function refundCredits(args:{workspaceId:string;credits:number;operationKey:string;description:string;metadata?:Record<string,unknown>}){return rpcBalance("refund_workspace_credits",{p_workspace_id:args.workspaceId,p_credits:args.credits,p_operation_key:args.operationKey,p_description:args.description,p_metadata:args.metadata??{}});}
export async function addPurchasedCredits(args:{workspaceId:string;credits:number;operationKey:string;description:string;metadata?:Record<string,unknown>}){return rpcBalance("add_purchased_credits",{p_workspace_id:args.workspaceId,p_credits:args.credits,p_operation_key:args.operationKey,p_description:args.description,p_metadata:args.metadata??{}});}
export async function getCreditBalance(workspaceId:string){const{url}=config();const response=await fetch(`${url}/rest/v1/credit_wallets?workspace_id=eq.${encodeURIComponent(workspaceId)}&select=balance&limit=1`,{headers:headers(),cache:"no-store"});if(!response.ok)throw new Error(await response.text());const rows=await response.json() as Array<{balance:number}>;return rows[0]?.balance??0;}

export function createSupabaseAiUsageStore():AiUsageStore{return{
 async append(record){const{url}=config();const row={id:record.id,workspace_id:record.workspaceId,site_id:record.siteId??null,build_id:record.buildId??null,task:record.task,profile_id:record.profileId,provider:record.provider,model:record.model,input_tokens:record.inputTokens??null,output_tokens:record.outputTokens??null,images:record.images??null,component_generations:record.componentGenerations??null,cost_microusd:record.costMicrousd,credits_charged:0,created_at:record.createdAt};const response=await fetch(`${url}/rest/v1/ai_usage`,{method:"POST",headers:{...headers(),Prefer:"return=minimal"},body:JSON.stringify(row)});if(!response.ok)throw new Error(await response.text());},
 async list(scope){const{url}=config();const q=new URLSearchParams({workspace_id:`eq.${scope.workspaceId}`,select:"*",order:"created_at.asc"});if(scope.siteId)q.set("site_id",`eq.${scope.siteId}`);if(scope.buildId)q.set("build_id",`eq.${scope.buildId}`);const response=await fetch(`${url}/rest/v1/ai_usage?${q}`,{headers:headers(),cache:"no-store"});if(!response.ok)throw new Error(await response.text());return(await response.json() as DbUsage[]).map(fromDb);}
};}

async function rpcBalance(name:string,body:Record<string,unknown>){const{url}=config();const response=await fetch(`${url}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(),body:JSON.stringify(body)});const text=await response.text();if(!response.ok){if(text.includes("INSUFFICIENT_CREDITS")){const error=new Error("INSUFFICIENT_CREDITS") as Error&{status?:number};error.status=402;throw error;}throw new Error(text||`${name} failed.`);}const parsed=JSON.parse(text) as number;return Number(parsed);}
type DbUsage={id:string;workspace_id:string;site_id?:string|null;build_id?:string|null;task:AiUsageRecord["task"];profile_id:string;provider:string;model:string;input_tokens?:number|null;output_tokens?:number|null;images?:number|null;component_generations?:number|null;cost_microusd:number;created_at:string};
function fromDb(row:DbUsage):AiUsageRecord{return{id:row.id,workspaceId:row.workspace_id,...(row.site_id?{siteId:row.site_id}:{}),...(row.build_id?{buildId:row.build_id}:{}),task:row.task,profileId:row.profile_id,provider:row.provider,model:row.model,...(row.input_tokens!=null?{inputTokens:row.input_tokens}:{}),...(row.output_tokens!=null?{outputTokens:row.output_tokens}:{}),...(row.images!=null?{images:row.images}:{}),...(row.component_generations!=null?{componentGenerations:row.component_generations}:{}),costMicrousd:Number(row.cost_microusd),createdAt:row.created_at};}
export type {AiUsageScope};
