import type { IndustryDesignPreset } from "./industry-design-preset-data";
import type { ThemeConfig } from "@micirql/schema";
const base={success:"#168a4a",warning:"#ad6a00",error:"#c93636"};
const t=(family:ThemeConfig["family"],primary:string,secondary:string,accent:string,bg:string,surface:string,display="Inter",density:"compact"|"comfortable"|"spacious"="comfortable",shape:"sharp"|"balanced"|"soft"="balanced",motion:"none"|"subtle"|"standard"|"rich"="subtle",mods:string[]=["light"]):ThemeConfig=>({family,modifiers:mods,brand:{colors:{primary,secondary,accent,background:bg,surface,textPrimary:secondary,textSecondary:"#667085",border:"#d8dde5",...base},typography:{display,body:"Inter",ui:"Inter"},density,shape,motion}});
const P=(id:string,name:string,description:string,theme:ThemeConfig,variants:IndustryDesignPreset["variants"]):IndustryDesignPreset=>({id,name,description,theme,variants});
export const CORPORATE_STARTUP_PRESETS:IndustryDesignPreset[]=[
P("enterprise-corporate","Enterprise / Institutional","Large-scale authority, governance and institutional credibility.",t("corporate","#234d78","#182534","#507ba6","#ffffff","#f3f6f8","Inter","compact","sharp"),{hero:2,about:2,features:3,services:2,team:3,testimonials:1,cta:2,contact:1}),
P("technology-corporate","Technology Corporate","Established technology company with innovation and enterprise trust.",t("futuristic","#365fd6","#17213a","#33a6c8","#f9fbff","#edf2ff","Inter","comfortable","balanced","standard",["light","gradient","motion-subtle"]),{hero:3,about:2,features:3,services:3,process:3,testimonials:2,cta:4,contact:2}),
P("industrial-manufacturing","Industrial / Manufacturing","Capability, facilities, quality and manufacturing scale.",t("corporate","#3f5968","#202a31","#d38a2f","#fcfcfa","#f0f2f1","Inter","compact","sharp","subtle",["light","sharp","photography-led"]),{hero:4,about:3,services:3,features:3,process:4,gallery:4,testimonials:1,cta:4,contact:2}),
P("engineering-corporate","Engineering / Infrastructure","Technical capability, projects and delivery confidence.",t("maximalist","#315a7a","#1d2831","#e09a36","#fbfcfc","#eff2f3","Inter","comfortable","sharp","standard",["geometric","sharp","photography-led"]),{hero:5,about:3,services:3,features:3,process:4,gallery:4,testimonials:2,cta:4,contact:2}),
P("b2b-services","B2B Services","Professional outcome-led corporate services and lead generation.",t("minimalist","#365f87","#23303e","#4e9a8d","#ffffff","#f2f6f7"),{hero:2,about:2,services:3,features:3,process:3,testimonials:2,cta:2,contact:1}),
P("holding-group","Group / Holding Company","Portfolio, subsidiaries, leadership and long-term institutional scale.",t("editorial","#303d4c","#191f26","#a58a60","#fdfcf9","#f1f0ec","Georgia","spacious","sharp"),{hero:4,about:4,features:2,services:2,team:3,gallery:4,cta:3,contact:2}),
P("global-corporate","Global / MNC","International footprint, capabilities and enterprise-grade authority.",t("corporate","#174f78","#162735","#4a89a8","#ffffff","#f2f6f8","Inter","compact","sharp"),{hero:2,about:3,features:3,services:2,team:3,testimonials:1,cta:2,contact:1}),
P("ai-startup","AI Startup","AI-native product storytelling with demos, capabilities and use cases.",t("futuristic","#7055e8","#17142b","#20c6c7","#faf9ff","#eeebff","Inter","comfortable","soft","rich",["gradient","motion-rich","geometric"]),{hero:5,features:4,services:4,process:3,gallery:4,testimonials:2,cta:5,contact:2}),
P("fintech-startup","Fintech Startup","Trust-first modern financial technology product presentation.",t("futuristic","#245fd1","#17233b","#24a783","#f8fbff","#ebf2ff","Inter","comfortable","soft","standard",["gradient","rounded","motion-subtle"]),{hero:3,features:3,services:2,process:3,testimonials:2,cta:4,contact:2}),
P("healthtech-startup","Healthtech Startup","Human, credible digital-health product storytelling.",t("minimalist","#177d83","#18363c","#4bb99c","#f8fdfc","#eaf6f3","Inter","comfortable","soft","standard",["light","rounded","photography-led"]),{hero:3,features:3,services:3,process:4,testimonials:3,cta:2,contact:2}),
P("edtech-startup","Edtech Startup","Friendly modern learning-product conversion and outcomes.",t("futuristic","#5b58d6","#28284a","#e49a3d","#fafaff","#efeffc","Inter","comfortable","soft","rich",["gradient","rounded","motion-rich"]),{hero:5,features:4,services:3,process:3,testimonials:3,cta:5,contact:2}),
P("marketplace-startup","Marketplace Startup","Two-sided marketplace value, categories and trust.",t("minimalist","#3568a6","#23344a","#e47e4b","#fbfcff","#eef3f8","Inter","comfortable","soft","standard",["light","rounded","photography-led"]),{hero:3,features:3,services:4,process:4,testimonials:3,gallery:4,cta:4,contact:2}),
P("consumer-app-startup","Consumer App Startup","High-energy app benefits, social proof and download conversion.",t("maximalist","#6c4ee8","#1e1933","#f45d76","#fbfaff","#efecff","Inter","comfortable","soft","rich",["gradient","rounded","motion-rich"]),{hero:5,features:4,gallery:4,process:3,testimonials:3,cta:5,contact:2}),
P("developer-api-startup","Developer / API Product","Technical clarity for APIs, developer tools and infrastructure products.",t("futuristic","#3e64d8","#131b2c","#28b8a7","#f9fbff","#edf1fa","Inter","compact","sharp","standard",["geometric","sharp","motion-subtle"]),{hero:2,features:3,services:2,process:2,testimonials:1,cta:4,contact:1}),
P("cybersecurity-startup","Cybersecurity Startup","Security authority, technical capability and enterprise confidence.",t("futuristic","#3569d4","#111a29","#22bca0","#f8faff","#eaf0f8","Inter","compact","sharp","standard",["geometric","sharp","gradient"]),{hero:4,features:3,services:3,process:4,testimonials:1,cta:4,contact:1}),
P("deeptech-startup","Deep-tech Startup","Research-led breakthrough technology with technical credibility.",t("futuristic","#514fc1","#191a31","#36a4a1","#fafaff","#eeeeF9","Inter","comfortable","sharp","standard",["geometric","gradient","motion-subtle"]),{hero:4,about:3,features:3,process:4,gallery:4,testimonials:1,cta:4,contact:2}),
P("climate-startup","Climate / Cleantech Startup","Mission-led climate technology with measurable impact.",t("organic","#31745b","#203c32","#d3a34a","#f9fcf8","#edf4eb","Inter","comfortable","soft","standard",["light","rounded","photography-led"]),{hero:3,about:3,features:3,services:3,process:4,gallery:4,testimonials:2,cta:4,contact:2}),
P("launch-startup","Early-stage Product Launch","Focused launch page for a new product, waitlist or first customers.",t("maximalist","#6550e8","#1c1830","#f06a55","#fbfaff","#efecff","Inter","comfortable","soft","rich",["gradient","motion-rich","rounded"]),{hero:5,features:4,process:3,testimonials:2,cta:5,contact:2})
];