import type { AssetRecord } from "@micirql/assets";

export const DEMO_ASSETS: AssetRecord[] = [
  {
    id: "mi-dental-calm-clinic",
    source: "micirql-placeholder",
    kind: "image",
    name: "Calm minimalist dental clinic",
    alt: "Empty modern dental treatment room with a white chair, cabinets, computer and clinical equipment",
    width: 1600,
    height: 1000,
    orientation: "landscape",
    aspectRatio: 1.6,
    focalPoint: { x: 0.58, y: 0.48 },
    domains: ["clinic"],
    subtypes: ["dental"],
    sectionFamilies: ["hero", "about"],
    themes: ["minimalist", "corporate", "glass", "organic"],
    tags: ["dental", "clinic", "interior", "calm", "minimalist", "non-human"],
    license: "licensed",
    sourceReference:
      "https://www.pexels.com/photo/a-dental-equipment-in-the-clinic-6812453/",
    originalUrl:
      "https://images.pexels.com/photos/6812453/pexels-photo-6812453.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1000",
    variants: [],
    active: true,
    createdAt: "2026-10-04T00:00:00.000Z",
  },
  {
    id: "mi-dental-smile-contour",
    source: "micirql-placeholder",
    kind: "image",
    name: "Bright modern dental equipment",
    alt: "Modern dental equipment arranged on a white counter in a bright treatment room",
    width: 1600,
    height: 1000,
    orientation: "landscape",
    aspectRatio: 1.6,
    focalPoint: { x: 0.6, y: 0.48 },
    domains: ["clinic"],
    subtypes: ["dental"],
    sectionFamilies: ["hero", "about"],
    themes: ["luxury", "cinematic", "organic", "playful"],
    tags: ["dental", "equipment", "bright", "modern", "clinical", "non-human"],
    license: "licensed",
    sourceReference:
      "https://www.pexels.com/photo/modern-dental-equipment-on-table-in-light-room-in-clinic-3845729/",
    originalUrl:
      "https://images.pexels.com/photos/3845729/pexels-photo-3845729.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1000",
    variants: [],
    active: true,
    createdAt: "2026-10-04T00:00:00.000Z",
  },
  {
    id: "mi-dental-precision-instruments",
    source: "micirql-placeholder",
    kind: "image",
    name: "Dental precision instruments",
    alt: "Close-up of stainless steel dental instruments mounted on clinical equipment",
    width: 1600,
    height: 1000,
    orientation: "landscape",
    aspectRatio: 1.6,
    focalPoint: { x: 0.56, y: 0.5 },
    domains: ["clinic"],
    subtypes: ["dental"],
    sectionFamilies: ["hero", "features"],
    themes: ["corporate", "futuristic", "maximalist", "glass"],
    tags: [
      "dental",
      "instrument",
      "precision",
      "technology",
      "detail",
      "non-human",
    ],
    license: "licensed",
    sourceReference:
      "https://www.pexels.com/photo/dental-equipment-on-machine-6809647/",
    originalUrl:
      "https://images.pexels.com/photos/6809647/pexels-photo-6809647.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1000",
    variants: [],
    active: true,
    createdAt: "2026-10-04T00:00:00.000Z",
  },
  {
    id: "mi-dental-editorial-pattern",
    source: "micirql-placeholder",
    kind: "image",
    name: "Editorial dental control detail",
    alt: "Close-up of the control panel on a modern dental treatment unit",
    width: 1600,
    height: 1000,
    orientation: "landscape",
    aspectRatio: 1.6,
    focalPoint: { x: 0.52, y: 0.5 },
    domains: ["clinic"],
    subtypes: ["dental"],
    sectionFamilies: ["hero", "gallery"],
    themes: ["editorial", "luxury", "minimalist", "playful"],
    tags: [
      "dental",
      "equipment",
      "control",
      "editorial",
      "detail",
      "non-human",
    ],
    license: "licensed",
    sourceReference:
      "https://www.pexels.com/photo/a-detail-shot-of-a-dentist-clinic-equipment-6812442/",
    originalUrl:
      "https://images.pexels.com/photos/6812442/pexels-photo-6812442.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1000",
    variants: [],
    active: true,
    createdAt: "2026-10-04T00:00:00.000Z",
  },
  {
    id: "mi-dental-documentary-clinic",
    source: "micirql-placeholder",
    kind: "image",
    name: "Documentary dental clinic",
    alt: "Modern empty dental treatment room with an X-ray displayed on a monitor",
    width: 1600,
    height: 1000,
    orientation: "landscape",
    aspectRatio: 1.6,
    focalPoint: { x: 0.56, y: 0.46 },
    domains: ["clinic"],
    subtypes: ["dental"],
    sectionFamilies: ["hero", "about", "gallery"],
    themes: ["editorial", "corporate", "playful", "glass"],
    tags: [
      "dental",
      "clinic",
      "x-ray",
      "equipment",
      "documentary",
      "non-human",
    ],
    license: "licensed",
    sourceReference:
      "https://www.pexels.com/photo/dental-clinic-and-equipment-4687337/",
    originalUrl:
      "https://images.pexels.com/photos/4687337/pexels-photo-4687337.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1000",
    variants: [],
    active: true,
    createdAt: "2026-10-04T00:00:00.000Z",
  },
  {
    id: "mi-dental-welcoming-clinic",
    source: "micirql-placeholder",
    kind: "image",
    name: "Welcoming dental clinic",
    alt: "Bright empty dental office with a treatment chair and organized clinical equipment",
    width: 1600,
    height: 1000,
    orientation: "landscape",
    aspectRatio: 1.6,
    focalPoint: { x: 0.52, y: 0.48 },
    domains: ["clinic"],
    subtypes: ["dental"],
    sectionFamilies: ["hero", "about", "gallery"],
    themes: ["minimalist", "organic", "playful", "cinematic"],
    tags: [
      "dental",
      "clinic",
      "interior",
      "welcoming",
      "organized",
      "non-human",
    ],
    license: "licensed",
    sourceReference:
      "https://www.pexels.com/photo/equipment-at-a-dentists-office-6812463/",
    originalUrl:
      "https://images.pexels.com/photos/6812463/pexels-photo-6812463.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1000",
    variants: [],
    active: true,
    createdAt: "2026-10-04T00:00:00.000Z",
  },
  {
    id: "mi-placeholder-clean-hero",
    source: "micirql-placeholder",
    kind: "illustration",
    name: "Abstract business interface",
    alt: "Abstract lavender business interface with layered cards and circles",
    width: 1600,
    height: 1000,
    orientation: "landscape",
    aspectRatio: 1.6,
    focalPoint: { x: 0.5, y: 0.45 },
    domains: ["landing-page", "corporate"],
    subtypes: [],
    sectionFamilies: ["hero", "about"],
    themes: ["minimalist", "corporate", "glass"],
    tags: ["business", "interface", "abstract", "geometric"],
    license: "micirql-owned",
    originalUrl: "/assets/placeholders/clean-hero.svg",
    variants: [],
    active: true,
    createdAt: "2026-08-15T00:00:00.000Z",
  },
  {
    id: "mi-placeholder-service-grid",
    source: "micirql-placeholder",
    kind: "image",
    name: "Service detail",
    alt: "Abstract professional service visual",
    width: 1200,
    height: 900,
    orientation: "landscape",
    aspectRatio: 1.333,
    focalPoint: { x: 0.5, y: 0.5 },
    domains: ["landing-page", "corporate", "construction", "education"],
    subtypes: [],
    sectionFamilies: ["services", "features"],
    themes: ["minimalist", "corporate", "editorial"],
    tags: ["service", "structured", "neutral"],
    license: "micirql-owned",
    originalUrl: "/assets/placeholders/service-grid.svg",
    variants: [],
    active: true,
    createdAt: "2026-08-15T00:00:00.000Z",
  },
  {
    id: "workspace-upload-demo",
    workspaceId: "workspace-demo",
    source: "user-upload",
    kind: "image",
    name: "My uploaded image",
    alt: "User uploaded workspace image",
    width: 1200,
    height: 800,
    orientation: "landscape",
    aspectRatio: 1.5,
    focalPoint: { x: 0.5, y: 0.5 },
    domains: [],
    subtypes: [],
    sectionFamilies: ["hero", "about", "services", "gallery"],
    themes: [],
    tags: ["upload"],
    license: "user-owned",
    originalUrl: "/assets/placeholders/user-upload.svg",
    variants: [],
    active: true,
    createdAt: "2026-08-15T00:00:00.000Z",
  },
];

export function demoAssetById(assetId: string) {
  return DEMO_ASSETS.find((asset) => asset.id === assetId);
}

export function addDemoAsset(asset: AssetRecord) {
  const existingIndex = DEMO_ASSETS.findIndex((item) => item.id === asset.id);
  if (existingIndex >= 0) DEMO_ASSETS[existingIndex] = asset;
  else DEMO_ASSETS.unshift(asset);
  return asset;
}
