import type { DentalMediaAspect, DentalMediaRole, DentalMediaSubindustry } from "./dental-media-library";

export type DentalMediaSeedSpec={id:string;certificationId:string;subindustry:DentalMediaSubindustry;role:DentalMediaRole;aspect:DentalMediaAspect;sectionFamily:"hero"|"services"|"features"|"process"|"about"|"gallery"|"cta";prompt:string;alt:string;tags:string[]};
const SAFETY="No text, logos, clinic branding, identifiable real staff, certificates, awards, fabricated facilities, fabricated equipment ownership, graphic procedures, or before-and-after claims.";
export const DENTAL_MEDIA_LIBRARY_V1_SEEDS:DentalMediaSeedSpec[]=[
{id:"general-hero-consultation",certificationId:"dental-general-care",subindustry:"general-dentistry",role:"hero",aspect:"wide",sectionFamily:"hero",prompt:`Premium editorial dental-care hero image, welcoming modern consultation between a generic dentist and adult patient, bright calm care environment, natural expressions, trustworthy contemporary healthcare photography, generous negative space for website headline. ${SAFETY}`,alt:"Welcoming modern dental consultation",tags:["dental","general-dentistry","hero","consultation","care","bright","welcoming"]},
{id:"general-services-smile",certificationId:"dental-general-care",subindustry:"general-dentistry",role:"services",aspect:"4:3",sectionFamily:"services",prompt:`Clean premium supporting visual for general dentistry services, natural healthy smile and calm preventive-care context, bright neutral clinical aesthetic, non-graphic, suitable for a treatment card or services section. ${SAFETY}`,alt:"General dental care and natural smile",tags:["dental","general-dentistry","services","natural-smile","preventive-care","bright"]},
{id:"general-process-care",certificationId:"dental-general-care",subindustry:"general-dentistry",role:"process",aspect:"16:9",sectionFamily:"process",prompt:`Premium non-graphic dental patient journey visual showing calm consultation, assessment and treatment-planning context, modern clean aesthetic, no specific clinic identity, suitable for a process section. ${SAFETY}`,alt:"Calm dental consultation and treatment-planning journey",tags:["dental","general-dentistry","process","consultation","treatment-planning","calm"]},
{id:"implant-hero-planning",certificationId:"dental-implant-authority",subindustry:"implant-dentistry",role:"hero",aspect:"wide",sectionFamily:"hero",prompt:`Premium implant dentistry hero image focused on adult consultation and digital treatment planning, confident precise modern restorative-care mood, sophisticated navy-friendly lighting, non-graphic, generous negative space for headline. ${SAFETY}`,alt:"Premium implant consultation and digital planning",tags:["dental","implant-dentistry","hero","implant-consultation","digital-planning","precision","premium"]},
{id:"implant-services-restorative",certificationId:"dental-implant-authority",subindustry:"implant-dentistry",role:"services",aspect:"4:3",sectionFamily:"services",prompt:`Premium supporting visual for implant and restorative dentistry, consultation-focused adult care, clean non-graphic restorative planning context, precise trustworthy editorial healthcare photography. ${SAFETY}`,alt:"Implant and restorative treatment planning",tags:["dental","implant-dentistry","services","restorative-care","implant-consultation","precision"]},
{id:"implant-tech-concept",certificationId:"dental-implant-authority",subindustry:"implant-dentistry",role:"technology",aspect:"16:9",sectionFamily:"features",prompt:`Elegant conceptual dental technology visual for implant planning, abstract digital scan and 3D planning atmosphere without showing a branded machine or implying equipment ownership, premium precise clinical aesthetic. ${SAFETY}`,alt:"Digital implant planning concept",tags:["dental","implant-dentistry","technology","digital-planning","3d-planning","precision"]},
{id:"cosmetic-hero-smile-design",certificationId:"dental-cosmetic-smile",subindustry:"cosmetic-dentistry",role:"hero",aspect:"wide",sectionFamily:"hero",prompt:`Warm premium cosmetic dentistry hero image, natural smile confidence and smile-design consultation mood, sophisticated editorial portraiture, realistic healthy smile, soft luxury healthcare aesthetic, negative space for website headline. ${SAFETY}`,alt:"Natural smile confidence and cosmetic consultation",tags:["dental","cosmetic-dentistry","hero","smile-design","natural-smile","warm","premium"]},
{id:"cosmetic-services-care",certificationId:"dental-cosmetic-smile",subindustry:"cosmetic-dentistry",role:"services",aspect:"4:3",sectionFamily:"services",prompt:`Tasteful premium supporting visual for cosmetic dentistry services such as smile design, veneers and whitening context without depicting a treatment outcome, natural warm healthcare photography. ${SAFETY}`,alt:"Cosmetic dentistry smile-design care",tags:["dental","cosmetic-dentistry","services","smile-design","veneers-context","whitening-context"]},
{id:"cosmetic-process-planning",certificationId:"dental-cosmetic-smile",subindustry:"cosmetic-dentistry",role:"process",aspect:"16:9",sectionFamily:"process",prompt:`Premium smile-design consultation journey visual, patient discussion and planning context, warm contemporary aesthetic, no before-and-after result, suitable for a cosmetic dentistry process section. ${SAFETY}`,alt:"Cosmetic smile-design consultation journey",tags:["dental","cosmetic-dentistry","process","smile-design","consultation","warm"]},
{id:"ortho-hero-aligner",certificationId:"dental-orthodontic-journey",subindustry:"orthodontics",role:"hero",aspect:"wide",sectionFamily:"hero",prompt:`Modern friendly orthodontic hero image with clear-aligner or braces consultation context, suitable for teen and adult care, bright progressive aesthetic, clean premium healthcare photography, negative space for headline. ${SAFETY}`,alt:"Modern orthodontic consultation",tags:["dental","orthodontics","hero","aligners","braces","consultation","modern"]},
{id:"ortho-services-options",certificationId:"dental-orthodontic-journey",subindustry:"orthodontics",role:"services",aspect:"4:3",sectionFamily:"services",prompt:`Premium orthodontic services visual showing generic clear-aligner and braces treatment context without identifiable patient outcomes, friendly modern clean aesthetic. ${SAFETY}`,alt:"Clear aligner and braces treatment options",tags:["dental","orthodontics","services","aligners","braces","adult-care","teen-care"]},
{id:"ortho-tech-scan",certificationId:"dental-orthodontic-journey",subindustry:"orthodontics",role:"technology",aspect:"16:9",sectionFamily:"features",prompt:`Conceptual orthodontic digital scanning and treatment-planning visual, modern precise aesthetic, no branded scanner and no implication that a specific clinic owns equipment. ${SAFETY}`,alt:"Orthodontic digital scanning concept",tags:["dental","orthodontics","technology","digital-scan","treatment-planning","modern"]},
{id:"endo-hero-reassurance",certificationId:"dental-endodontic-precision",subindustry:"endodontics",role:"hero",aspect:"wide",sectionFamily:"hero",prompt:`Calm premium endodontic hero image focused on specialist consultation, reassurance and tooth-preservation care, precise modern clinical atmosphere, non-graphic, negative space for website headline. ${SAFETY}`,alt:"Calm endodontic specialist consultation",tags:["dental","endodontics","hero","root-canal-context","tooth-preservation","precision-care","calm"]},
{id:"endo-services-preservation",certificationId:"dental-endodontic-precision",subindustry:"endodontics",role:"services",aspect:"4:3",sectionFamily:"services",prompt:`Premium non-graphic supporting visual for root-canal and tooth-preservation services, calm specialist dental context, clean precise healthcare editorial style. ${SAFETY}`,alt:"Tooth-preservation and endodontic care",tags:["dental","endodontics","services","root-canal-context","tooth-preservation","precision-care"]},
{id:"endo-tech-precision",certificationId:"dental-endodontic-precision",subindustry:"endodontics",role:"technology",aspect:"16:9",sectionFamily:"features",prompt:`Elegant conceptual precision-dentistry visual for endodontic technology and magnification, abstract clinical detail without branded equipment or ownership claims, calm specialist aesthetic. ${SAFETY}`,alt:"Precision endodontic technology concept",tags:["dental","endodontics","technology","precision-care","tooth-preservation","specialist"]}
];
