import type { ThemeConfig } from "@micirql/schema";
import type { SectionFamily, SectionVariant } from "@micirql/sections";

export type IndustryDesignPreset = { id:string; name:string; description:string; theme:ThemeConfig; variants:Partial<Record<SectionFamily, SectionVariant>> };
const baseColors={success:"#168a4a",warning:"#ad6a00",error:"#c93636"};
const theme=(family:ThemeConfig["family"],modifiers:string[],primary:string,secondary:string,accent:string,background:string,surface:string,textPrimary:string,textSecondary:string,border:string,display="Inter",density:"compact"|"comfortable"|"spacious"="comfortable",shape:"sharp"|"balanced"|"soft"="balanced",motion:"none"|"subtle"|"standard"|"rich"="subtle"):ThemeConfig=>({family,modifiers,brand:{colors:{primary,secondary,accent,background,surface,textPrimary,textSecondary,border,...baseColors},typography:{display,body:"Inter",ui:"Inter"},density,shape,motion}});
export const INDUSTRY_DESIGN_PRESETS:IndustryDesignPreset[]=[
{id:"dental-clinic",name:"Dental Clinic",description:"Clean, reassuring general dentistry.",theme:theme("minimalist",["light","rounded","photography-led"],"#0f766e","#164e63","#14b8a6","#f8fffe","#edf9f7","#102a2a","#527070","#cfe3df","Inter","comfortable","soft"),variants:{hero:2,services:3,testimonials:2,gallery:3,cta:2,contact:2}},
{id:"premium-implant-clinic",name:"Premium Implant Clinic",description:"High-trust implant-led practice.",theme:theme("luxury",["light","photography-led","motion-subtle"],"#8b6b35","#15120e","#c4a266","#fffdf9","#f6f1e8","#1c1812","#746a5c","#ded3c0","Georgia","spacious","balanced"),variants:{hero:5,about:4,services:2,process:4,testimonials:4,gallery:5,cta:3,contact:2}},
{id:"medical-clinic",name:"Medical Clinic",description:"Calm credible medical care.",theme:theme("minimalist",["light","rounded","photography-led"],"#176b87","#17324a","#2ea7a0","#f9fcfd","#edf6f8","#172b35","#61747d","#d2e2e7","Inter","comfortable","soft"),variants:{hero:2,about:2,services:3,team:3,process:2,testimonials:2,cta:2,contact:2}},
{id:"physiotherapy",name:"Physiotherapy / Rehabilitation",description:"Active reassuring rehabilitation.",theme:theme("organic",["light","rounded","photography-led"],"#237a63","#24443d","#66ad7d","#fbfdf9","#edf5ec","#1f332d","#63766f","#d4e1d7","Inter","comfortable","soft","standard"),variants:{hero:3,about:2,services:3,features:2,process:4,testimonials:3,cta:2,contact:2}},
{id:"dermatology",name:"Dermatology / Aesthetics",description:"Refined clinical aesthetics.",theme:theme("luxury",["light","photography-led"],"#8b625d","#332724","#c69a8c","#fffaf8","#f6ece8","#302421","#796964","#e3d3ce","Georgia","spacious","soft"),variants:{hero:5,about:4,services:2,features:2,gallery:5,testimonials:4,cta:3,contact:2}},
{id:"mental-wellness",name:"Therapy / Mental Wellness",description:"Warm private human care.",theme:theme("organic",["light","rounded","texture-grain"],"#5f7667","#39483e","#b18b67","#fcfaf5","#f1eee5","#2d352f","#72776f","#dedbd1","Georgia","spacious","soft"),variants:{hero:4,about:4,services:2,process:2,testimonials:3,cta:2,contact:2}},
{id:"nutrition-wellness",name:"Nutrition / Wellness",description:"Fresh educational wellness.",theme:theme("organic",["light","rounded","photography-led"],"#557a3d","#34472d","#d29b54","#fdfcf7","#f1f4e9","#293327","#6c7567","#dce1d3","Georgia","comfortable","soft","standard"),variants:{hero:3,about:3,services:4,features:2,process:3,testimonials:3,cta:2,contact:2}},
{id:"fitness",name:"Fitness / Gym",description:"Energetic performance-led fitness.",theme:theme("maximalist",["geometric","sharp","motion-rich"],"#e4562b","#171a1f","#f5a623","#fbfbfa","#f1eee9","#181b20","#666b72","#d9d9d6","Inter","comfortable","sharp","rich"),variants:{hero:5,about:3,services:4,features:3,process:4,testimonials:2,gallery:4,cta:5,contact:2}},
{id:"yoga-spa",name:"Yoga / Spa / Wellness",description:"Serene restorative wellness.",theme:theme("organic",["light","photography-led","texture-grain"],"#7a6d58","#3d3932","#b9a47e","#fdfbf6","#f1ede4","#332f29","#756e63","#dfd8cb","Georgia","spacious","soft"),variants:{hero:5,about:4,services:3,gallery:5,testimonials:4,cta:3,contact:2}},
{id:"veterinary",name:"Veterinary Clinic",description:"Friendly trusted pet care.",theme:theme("organic",["light","rounded","photography-led"],"#26786d","#294b48","#e09b55","#fbfdfb","#edf6f2","#233532","#687b77","#d3e3de","Inter","comfortable","soft","standard"),variants:{hero:3,about:2,services:3,team:2,features:2,testimonials:3,cta:2,contact:2}},
{id:"salon-beauty",name:"Salon / Barber / Beauty",description:"Stylish booking-led local beauty services.",theme:theme("luxury",["photography-led","motion-subtle"],"#7b4b57","#292126","#c79382","#fffafa","#f6ecee","#2b2226","#796b70","#e4d4d8","Georgia","spacious","soft"),variants:{hero:5,about:3,services:4,gallery:5,testimonials:4,cta:3,contact:2}},
{id:"home-services",name:"Home Services",description:"Fast trustworthy presentation for plumbers, electricians, HVAC, cleaning and repair services.",theme:theme("corporate",["light","sharp","photography-led"],"#1769aa","#1d2935","#f0a128","#ffffff","#f3f6f8","#17232e","#66727d","#d7dfe5","Inter","compact","sharp","subtle"),variants:{hero:2,services:3,features:3,process:2,testimonials:2,cta:4,contact:1}},
{id:"automotive",name:"Automotive Services",description:"Strong practical presentation for repair, detailing and automotive specialists.",theme:theme("maximalist",["geometric","sharp","photography-led"],"#c33b2d","#171b20","#e79b35","#fbfbfa","#eeefef","#181c20","#686e73","#d6d8da","Inter","comfortable","sharp","standard"),variants:{hero:5,services:3,features:3,gallery:4,process:4,testimonials:2,cta:4,contact:2}},
{id:"legal",name:"Law Firm / Legal",description:"Authoritative restrained presentation for lawyers and legal practices.",theme:theme("corporate",["light","sharp","motion-subtle"],"#243c5a","#17202b","#a8864f","#fdfdfc","#f2f3f4","#171e27","#66717c","#d7dbe0","Georgia","comfortable","sharp"),variants:{hero:4,about:2,services:2,features:2,team:3,testimonials:1,cta:2,contact:1}},
{id:"finance-accounting",name:"Accounting / Finance",description:"Precise trustworthy presentation for accountants, CAs and financial advisers.",theme:theme("corporate",["light","sharp"],"#245b55","#203431","#a4874d","#ffffff","#f2f6f5","#1d2b29","#65736f","#d7e0de","Inter","compact","sharp"),variants:{hero:2,about:2,services:2,features:3,process:2,testimonials:1,cta:2,contact:1}},
{id:"consulting",name:"Consulting / Advisory",description:"Strategic polished presentation for consultants and advisory firms.",theme:theme("editorial",["light","sharp","motion-subtle"],"#36506d","#1c2733","#b28a5b","#fdfcf9","#f1f0ec","#1b2229","#69727a","#d9d8d3","Georgia","spacious","sharp"),variants:{hero:4,about:3,services:2,features:2,process:3,testimonials:4,cta:3,contact:2}},
{id:"recruitment",name:"Recruitment / Staffing",description:"People-first credible presentation for recruitment and staffing agencies.",theme:theme("minimalist",["light","rounded","photography-led"],"#4169a1","#26364b","#5ba6a0","#fbfcfe","#eef3f8","#202d3d","#697787","#d6e0e9","Inter","comfortable","soft"),variants:{hero:3,about:2,services:3,features:3,process:4,testimonials:2,cta:2,contact:2}},
{id:"insurance",name:"Insurance",description:"Reassuring conversion-focused presentation for insurance advisers and agencies.",theme:theme("corporate",["light","rounded"],"#27658a","#263b4a","#4b9a78","#ffffff","#f1f6f8","#20303a","#687983","#d7e2e7","Inter","comfortable","soft"),variants:{hero:2,services:3,features:2,process:2,testimonials:2,cta:2,contact:1}},
{id:"marketing-agency",name:"Marketing / Digital Agency",description:"Bold results-led presentation for marketing, growth and digital agencies.",theme:theme("maximalist",["gradient","geometric","motion-rich"],"#6b46e5","#181526","#f05c4f","#fbfaff","#efecff","#191624","#6d6878","#d9d3ef","Inter","comfortable","balanced","rich"),variants:{hero:5,about:3,services:4,features:3,process:4,gallery:4,testimonials:2,cta:5,contact:2}},
{id:"artist",name:"Artist / Fine Art",description:"Gallery-first editorial art.",theme:theme("editorial",["light","photography-led"],"#181715","#6b6258","#a85f3d","#fbfaf6","#f0ede6","#171613","#716d66","#d9d4ca","Georgia","spacious"),variants:{hero:4,about:4,gallery:5,features:2,testimonials:4,cta:3,contact:2}},
{id:"photographer",name:"Photographer",description:"Image-dominant visual storytelling.",theme:theme("minimalist",["photography-led","sharp"],"#171717","#4a4a4a","#8d7358","#fcfcfb","#f1f0ed","#161616","#686868","#d9d7d2","Georgia","spacious","sharp"),variants:{hero:5,about:2,gallery:5,services:2,testimonials:3,cta:2,contact:2}},
{id:"creative-studio",name:"Creative Studio",description:"Bold multidisciplinary portfolio.",theme:theme("maximalist",["geometric","photography-led","motion-rich"],"#5b36f2","#15131c","#ff6b45","#faf9ff","#eeebff","#17151e","#6b6675","#d8d2ee","Inter","comfortable","balanced","rich"),variants:{hero:5,about:3,services:4,features:3,gallery:4,process:4,testimonials:2,cta:5,contact:2}},
{id:"musician",name:"Musician / Performer",description:"Expressive performance presentation.",theme:theme("futuristic",["gradient","motion-rich","photography-led"],"#7c3aed","#15111d","#f43f5e","#faf8ff","#f0eaff","#18121f","#706579","#ddd2e8","Inter","comfortable","soft","rich"),variants:{hero:5,about:3,features:4,gallery:5,testimonials:3,cta:5,contact:2}},
{id:"restaurant",name:"Restaurant",description:"Warm image-led hospitality.",theme:theme("organic",["photography-led","texture-grain","rounded"],"#8a3d21","#342319","#d18a4e","#fffaf3","#f5eadc","#2d2119","#776354","#dfd0be","Georgia","comfortable","soft","standard"),variants:{hero:5,about:2,services:4,gallery:5,testimonials:3,cta:2,contact:3}},
{id:"real-estate",name:"Real Estate",description:"Editorial property presentation.",theme:theme("editorial",["light","photography-led","sharp"],"#25364a","#0f1720","#b58a55","#fbfaf7","#f0eee9","#14191f","#65707a","#d8d7d2","Georgia","spacious","sharp"),variants:{hero:4,features:2,gallery:5,process:2,testimonials:4,cta:3,contact:2}},
{id:"saas",name:"SaaS",description:"Crisp product-led software.",theme:theme("futuristic",["gradient","rounded","motion-rich"],"#6d5dfc","#111827","#22d3ee","#f8faff","#eef2ff","#111827","#667085","#d9def2","Inter","comfortable","soft","rich"),variants:{hero:2,features:3,process:2,testimonials:2,cta:5,contact:1}},
{id:"corporate",name:"Corporate",description:"Structured established business.",theme:theme("corporate",["light","sharp"],"#1f4b7a","#17212b","#4d7ba8","#ffffff","#f4f6f8","#17212b","#687481","#d9dee4","Inter","compact","sharp"),variants:{hero:2,about:2,services:2,process:1,testimonials:1,cta:2,contact:1}},
{id:"construction",name:"Construction",description:"Strong project-led construction.",theme:theme("maximalist",["geometric","sharp","photography-led"],"#d97706","#1f2937","#f59e0b","#fffdf8","#f5f1e8","#1c232b","#69727c","#d9d3c8","Inter","comfortable","sharp","standard"),variants:{hero:5,about:3,services:3,process:4,gallery:4,testimonials:2,cta:4,contact:2}}
];
