import type { ThemeConfig } from "@micirql/schema";
import type { SectionFamily, SectionVariant } from "@micirql/sections";
export type IndustryDesignPreset={id:string;name:string;description:string;theme:ThemeConfig;variants:Partial<Record<SectionFamily,SectionVariant>>};
const baseColors={success:"#168a4a",warning:"#ad6a00",error:"#c93636"};
type ThemeModifier=ThemeConfig["modifiers"][number];
const theme=(family:ThemeConfig["family"],modifiers:ThemeModifier[],primary:string,secondary:string,accent:string,background:string,surface:string,textPrimary:string,textSecondary:string,border:string,display="Inter",density:"compact"|"comfortable"|"spacious"="comfortable",shape:"sharp"|"balanced"|"soft"="balanced",motion:"none"|"subtle"|"standard"|"rich"="subtle"):ThemeConfig=>({family,modifiers,brand:{colors:{primary,secondary,accent,background,surface,textPrimary,textSecondary,border,...baseColors},typography:{display,body:"Inter",ui:"Inter"},density,shape,motion}});
const P=(id:string,name:string,description:string,t:ThemeConfig,variants:IndustryDesignPreset["variants"]):IndustryDesignPreset=>({id,name,description,theme:t,variants});
export const INDUSTRY_DESIGN_PRESETS:IndustryDesignPreset[]=[
P("dental-clinic","Dental Clinic","Clean reassuring general dentistry.",theme("minimalist",["light","rounded","photography-led"],"#0f766e","#164e63","#14b8a6","#f8fffe","#edf9f7","#102a2a","#527070","#cfe3df","Inter","comfortable","soft"),{hero:2,services:3,testimonials:2,gallery:3,cta:2,contact:2}),
P("premium-implant-clinic","Premium Implant Clinic","High-trust implant practice.",theme("luxury",["light","photography-led"],"#8b6b35","#15120e","#c4a266","#fffdf9","#f6f1e8","#1c1812","#746a5c","#ded3c0","Georgia","spacious"),{hero:5,about:4,services:2,process:4,testimonials:4,gallery:5,cta:3,contact:2}),
P("medical-clinic","Medical Clinic","Calm credible medical care.",theme("minimalist",["light","rounded","photography-led"],"#176b87","#17324a","#2ea7a0","#f9fcfd","#edf6f8","#172b35","#61747d","#d2e2e7","Inter","comfortable","soft"),{hero:2,about:2,services:3,team:3,process:2,testimonials:2,cta:2,contact:2}),
P("physiotherapy","Physiotherapy / Rehabilitation","Active reassuring rehabilitation.",theme("organic",["light","rounded","photography-led"],"#237a63","#24443d","#66ad7d","#fbfdf9","#edf5ec","#1f332d","#63766f","#d4e1d7","Inter","comfortable","soft","standard"),{hero:3,about:2,services:3,features:2,process:4,testimonials:3,cta:2,contact:2}),
P("dermatology","Dermatology / Aesthetics","Refined clinical aesthetics.",theme("luxury",["light","photography-led"],"#8b625d","#332724","#c69a8c","#fffaf8","#f6ece8","#302421","#796964","#e3d3ce","Georgia","spacious","soft"),{hero:5,about:4,services:2,features:2,gallery:5,testimonials:4,cta:3,contact:2}),
P("mental-wellness","Therapy / Mental Wellness","Warm private human care.",theme("organic",["light","rounded","texture-grain"],"#5f7667","#39483e","#b18b67","#fcfaf5","#f1eee5","#2d352f","#72776f","#dedbd1","Georgia","spacious","soft"),{hero:4,about:4,services:2,process:2,testimonials:3,cta:2,contact:2}),
P("nutrition-wellness","Nutrition / Wellness","Fresh educational wellness.",theme("organic",["light","rounded","photography-led"],"#557a3d","#34472d","#d29b54","#fdfcf7","#f1f4e9","#293327","#6c7567","#dce1d3","Georgia","comfortable","soft","standard"),{hero:3,about:3,services:4,features:2,process:3,testimonials:3,cta:2,contact:2}),
P("fitness","Fitness / Gym","Energetic performance fitness.",theme("maximalist",["geometric","sharp","motion-rich"],"#e4562b","#171a1f","#f5a623","#fbfbfa","#f1eee9","#181b20","#666b72","#d9d9d6","Inter","comfortable","sharp","rich"),{hero:5,about:3,services:4,features:3,process:4,testimonials:2,gallery:4,cta:5,contact:2}),
P("yoga-spa","Yoga / Spa / Wellness","Serene restorative wellness.",theme("organic",["light","photography-led","texture-grain"],"#7a6d58","#3d3932","#b9a47e","#fdfbf6","#f1ede4","#332f29","#756e63","#dfd8cb","Georgia","spacious","soft"),{hero:5,about:4,services:3,gallery:5,testimonials:4,cta:3,contact:2}),
P("veterinary","Veterinary Clinic","Friendly trusted pet care.",theme("organic",["light","rounded","photography-led"],"#26786d","#294b48","#e09b55","#fbfdfb","#edf6f2","#233532","#687b77","#d3e3de","Inter","comfortable","soft","standard"),{hero:3,about:2,services:3,team:2,features:2,testimonials:3,cta:2,contact:2}),
P("salon-beauty","Salon / Barber / Beauty","Stylish booking-led beauty.",theme("luxury",["photography-led"],"#7b4b57","#292126","#c79382","#fffafa","#f6ecee","#2b2226","#796b70","#e4d4d8","Georgia","spacious","soft"),{hero:5,about:3,services:4,gallery:5,testimonials:4,cta:3,contact:2}),
P("home-services","Home Services","Fast trustworthy local trades.",theme("corporate",["light","sharp","photography-led"],"#1769aa","#1d2935","#f0a128","#ffffff","#f3f6f8","#17232e","#66727d","#d7dfe5","Inter","compact","sharp"),{hero:2,services:3,features:3,process:2,testimonials:2,cta:4,contact:1}),
P("automotive","Automotive Services","Strong practical automotive service.",theme("maximalist",["geometric","sharp","photography-led"],"#c33b2d","#171b20","#e79b35","#fbfbfa","#eeefef","#181c20","#686e73","#d6d8da","Inter","comfortable","sharp","standard"),{hero:5,services:3,features:3,gallery:4,process:4,testimonials:2,cta:4,contact:2}),
P("legal","Law Firm / Legal","Authoritative restrained legal practice.",theme("corporate",["light","sharp"],"#243c5a","#17202b","#a8864f","#fdfdfc","#f2f3f4","#171e27","#66717c","#d7dbe0","Georgia","comfortable","sharp"),{hero:4,about:2,services:2,features:2,team:3,testimonials:1,cta:2,contact:1}),
P("finance-accounting","Accounting / Finance","Precise trustworthy financial services.",theme("corporate",["light","sharp"],"#245b55","#203431","#a4874d","#ffffff","#f2f6f5","#1d2b29","#65736f","#d7e0de","Inter","compact","sharp"),{hero:2,about:2,services:2,features:3,process:2,testimonials:1,cta:2,contact:1}),
P("consulting","Consulting / Advisory","Strategic polished advisory.",theme("editorial",["light","sharp"],"#36506d","#1c2733","#b28a5b","#fdfcf9","#f1f0ec","#1b2229","#69727a","#d9d8d3","Georgia","spacious","sharp"),{hero:4,about:3,services:2,features:2,process:3,testimonials:4,cta:3,contact:2}),
P("recruitment","Recruitment / Staffing","People-first recruitment.",theme("minimalist",["light","rounded","photography-led"],"#4169a1","#26364b","#5ba6a0","#fbfcfe","#eef3f8","#202d3d","#697787","#d6e0e9","Inter","comfortable","soft"),{hero:3,about:2,services:3,features:3,process:4,testimonials:2,cta:2,contact:2}),
P("insurance","Insurance","Reassuring insurance services.",theme("corporate",["light","rounded"],"#27658a","#263b4a","#4b9a78","#ffffff","#f1f6f8","#20303a","#687983","#d7e2e7","Inter","comfortable","soft"),{hero:2,services:3,features:2,process:2,testimonials:2,cta:2,contact:1}),
P("marketing-agency","Marketing / Digital Agency","Bold results-led agency.",theme("maximalist",["gradient","geometric","motion-rich"],"#6b46e5","#181526","#f05c4f","#fbfaff","#efecff","#191624","#6d6878","#d9d3ef","Inter","comfortable","balanced","rich"),{hero:5,about:3,services:4,features:3,process:4,gallery:4,testimonials:2,cta:5,contact:2}),
P("hotel-resort","Hotel / Resort","Immersive destination-led hospitality for hotels, resorts and stays.",theme("luxury",["photography-led","motion-subtle"],"#42605b","#262f2d","#b99763","#fdfbf6","#f1eee7","#252b29","#6f7773","#ddd8ce","Georgia","spacious","soft"),{hero:5,about:4,features:2,gallery:5,services:3,testimonials:4,cta:3,contact:2}),
P("bakery-catering","Bakery / Catering","Warm appetite-led presentation for bakeries, caterers and food brands.",theme("organic",["photography-led","rounded","texture-grain"],"#9b573f","#4a332a","#d49b62","#fffaf3","#f6eadc","#352821","#78675d","#e2d2c1","Georgia","comfortable","soft","standard"),{hero:5,about:2,services:4,gallery:5,testimonials:3,cta:2,contact:3}),
P("events-wedding","Events / Wedding","Elegant emotional storytelling for planners, venues and event professionals.",theme("luxury",["photography-led","motion-subtle"],"#82666d","#332b2e","#c2a174","#fffafa","#f4eeee","#30282a","#766b6e","#e1d6d8","Georgia","spacious","soft"),{hero:5,about:4,services:3,gallery:5,process:3,testimonials:4,cta:3,contact:2}),
P("travel-tourism","Travel / Tours","Exploratory image-rich presentation for travel companies and tour operators.",theme("organic",["photography-led","rounded","motion-rich"],"#167b87","#23464c","#e49b48","#f8fdfd","#eaf5f4","#1f3437","#65787b","#d0e2e2","Inter","comfortable","soft","rich"),{hero:5,services:4,features:3,gallery:5,process:4,testimonials:3,cta:5,contact:2}),
P("school-education","School / Education","Friendly credible presentation for schools and learning institutions.",theme("minimalist",["light","rounded","photography-led"],"#3569a8","#263a54","#e6a63f","#fbfcff","#eef3f9","#202d3e","#68778a","#d6e0eb","Inter","comfortable","soft","standard"),{hero:3,about:2,features:3,services:3,team:2,gallery:4,testimonials:3,cta:2,contact:2}),
P("coaching-training","Coaching / Training","Outcome-led learning presentation for tutors, coaching centres and training institutes.",theme("corporate",["light","rounded"],"#4b5db5","#2a3150","#df8c42","#fbfbff","#eff0fa","#252a40","#6c7187","#dadcec","Inter","comfortable","soft","standard"),{hero:2,about:2,services:3,features:3,process:4,testimonials:2,cta:4,contact:2}),
P("online-course","Online Course / Educator","Modern creator-led learning and course conversion.",theme("futuristic",["gradient","rounded","motion-rich"],"#6552d9","#24203a","#22a8a2","#faf9ff","#eeebff","#211e31","#6c677c","#d9d4ed","Inter","comfortable","soft","rich"),{hero:5,about:3,features:4,services:4,process:3,testimonials:3,cta:5,contact:2}),
P("ecommerce-brand","Ecommerce Brand","Conversion-led product storytelling for modern online brands.",theme("minimalist",["light","photography-led","rounded"],"#292929","#484848","#d46b4c","#ffffff","#f5f4f2","#1d1d1d","#6c6c6c","#dedbd6","Inter","comfortable","soft","standard"),{hero:3,features:3,gallery:4,testimonials:3,cta:4,contact:2}),
P("fashion-brand","Fashion / Apparel","Editorial image-first presentation for fashion and apparel brands.",theme("editorial",["photography-led","sharp","motion-subtle"],"#1c1b1a","#56504b","#9e6f59","#fcfbf8","#f0eee9","#191817","#706b66","#d8d4cc","Georgia","spacious","sharp"),{hero:5,about:4,gallery:5,features:2,testimonials:4,cta:3,contact:2}),
P("jewellery","Jewellery / Luxury Goods","Refined high-value product presentation for jewellery and luxury goods.",theme("luxury",["photography-led","motion-subtle"],"#8a7043","#211e19","#c5a668","#fffdf8","#f3efe5","#211d18","#766d5f","#dfd6c5","Georgia","spacious","balanced"),{hero:5,about:4,gallery:5,features:2,testimonials:4,cta:3,contact:2}),
P("furniture-interiors","Furniture / Home Brand","Architectural product-led presentation for furniture and home brands.",theme("editorial",["photography-led","sharp"],"#675b4e","#312d29","#a98b66","#fbfaf7","#efede8","#2a2724","#706b64","#d9d5cd","Georgia","spacious","sharp"),{hero:4,about:3,gallery:5,features:3,services:2,testimonials:4,cta:3,contact:2}),
P("beauty-brand","Beauty / Skincare Brand","Soft premium product storytelling for skincare and beauty brands.",theme("luxury",["photography-led","rounded"],"#986b73","#382d31","#d7a58e","#fffafa","#f7eeee","#30272a","#796c70","#e6d8db","Georgia","spacious","soft"),{hero:5,about:4,gallery:5,features:3,testimonials:4,cta:3,contact:2}),
P("artist","Artist / Fine Art","Gallery-first editorial art.",theme("editorial",["light","photography-led"],"#181715","#6b6258","#a85f3d","#fbfaf6","#f0ede6","#171613","#716d66","#d9d4ca","Georgia","spacious"),{hero:4,about:4,gallery:5,features:2,testimonials:4,cta:3,contact:2}),
P("photographer","Photographer","Image-dominant visual storytelling.",theme("minimalist",["photography-led","sharp"],"#171717","#4a4a4a","#8d7358","#fcfcfb","#f1f0ed","#161616","#686868","#d9d7d2","Georgia","spacious","sharp"),{hero:5,about:2,gallery:5,services:2,testimonials:3,cta:2,contact:2}),
P("creative-studio","Creative Studio","Bold multidisciplinary portfolio.",theme("maximalist",["geometric","photography-led","motion-rich"],"#5b36f2","#15131c","#ff6b45","#faf9ff","#eeebff","#17151e","#6b6675","#d8d2ee","Inter","comfortable","balanced","rich"),{hero:5,about:3,services:4,features:3,gallery:4,process:4,testimonials:2,cta:5,contact:2}),
P("musician","Musician / Performer","Expressive performance presentation.",theme("futuristic",["gradient","motion-rich","photography-led"],"#7c3aed","#15111d","#f43f5e","#faf8ff","#f0eaff","#18121f","#706579","#ddd2e8","Inter","comfortable","soft","rich"),{hero:5,about:3,features:4,gallery:5,testimonials:3,cta:5,contact:2}),
P("restaurant","Restaurant","Warm image-led hospitality.",theme("organic",["photography-led","texture-grain","rounded"],"#8a3d21","#342319","#d18a4e","#fffaf3","#f5eadc","#2d2119","#776354","#dfd0be","Georgia","comfortable","soft","standard"),{hero:5,about:2,services:4,gallery:5,testimonials:3,cta:2,contact:3}),
P("real-estate","Real Estate","Editorial property presentation.",theme("editorial",["light","photography-led","sharp"],"#25364a","#0f1720","#b58a55","#fbfaf7","#f0eee9","#14191f","#65707a","#d8d7d2","Georgia","spacious","sharp"),{hero:4,features:2,gallery:5,process:2,testimonials:4,cta:3,contact:2}),
P("saas","SaaS","Crisp product-led software.",theme("futuristic",["gradient","rounded","motion-rich"],"#6d5dfc","#111827","#22d3ee","#f8faff","#eef2ff","#111827","#667085","#d9def2","Inter","comfortable","soft","rich"),{hero:2,features:3,process:2,testimonials:2,cta:5,contact:1}),
P("corporate","Corporate","Structured established business.",theme("corporate",["light","sharp"],"#1f4b7a","#17212b","#4d7ba8","#ffffff","#f4f6f8","#17212b","#687481","#d9dee4","Inter","compact","sharp"),{hero:2,about:2,services:2,process:1,testimonials:1,cta:2,contact:1}),
P("construction","Construction","Strong project-led construction.",theme("maximalist",["geometric","sharp","photography-led"],"#d97706","#1f2937","#f59e0b","#fffdf8","#f5f1e8","#1c232b","#69727c","#d9d3c8","Inter","comfortable","sharp","standard"),{hero:5,about:3,services:3,process:4,gallery:4,testimonials:2,cta:4,contact:2})
];