"use client";
import { useEffect,useState } from "react";
import type { SupabaseSession } from "./auth-client";
import { OnboardingGate } from "./onboarding-gate";
import styles from "./project-dashboard.module.css";

type Project={id:string;workspace_id:string;name:string;status:string;published_version_id:string|null;updated_at:string;draft?:{revision:number;updated_at:string}|null;hostname?:{hostname:string;status:string;ssl_status:string}|null};
export function ProjectDashboard({session}:{session:SupabaseSession}){
 const [projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState<Project|null>(null);
 const authHeaders=()=>({Authorization:`Bearer ${session.access_token}`});
 async function load(){setLoading(true);try{const r=await fetch("/api/projects",{cache:"no-store",headers:authHeaders()});const p=await r.json();if(!r.ok)throw new Error(p.error??"Could not load projects.");setProjects(p.projects??[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load projects.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[session.access_token]);
 async function create(){const name=window.prompt("Website name","Untitled website")?.trim();if(!name)return;const r=await fetch("/api/projects",{method:"POST",headers:{...authHeaders(),"content-type":"application/json"},body:JSON.stringify({action:"create",name})});const p=await r.json();if(!r.ok||!p.project){setError(p.error??"Could not create site.");return}setError("");setOpen({...p.project,status:"draft",published_version_id:null,updated_at:new Date().toISOString()})}
 async function rename(project:Project){const name=window.prompt("Rename website",project.name)?.trim();if(!name||name===project.name)return;await mutate({siteId:project.id,name});}
 async function duplicate(project:Project){const r=await fetch("/api/projects",{method:"POST",headers:{...authHeaders(),"content-type":"application/json"},body:JSON.stringify({action:"duplicate",workspaceId:project.workspace_id,siteId:project.id,name:`${project.name} Copy`})});const p=await r.json();if(!r.ok){setError(p.error??"Duplicate failed.");return}setError("");await load()}
 async function archive(project:Project){if(!window.confirm(`Archive ${project.name}?`))return;await mutate({siteId:project.id,archived:true})}
 async function mutate(body:Record<string,unknown>){const r=await fetch("/api/projects",{method:"PATCH",headers:{...authHeaders(),"content-type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok){setError(p.error??"Update failed.");return}setError("");await load()}
 if(open)return <OnboardingGate session={session} initialWorkspaceId={open.workspace_id} initialSiteId={open.id} onBack={()=>{setOpen(null);void load()}}/>;
 return <main className={styles.shell}><header className={styles.header}><div><span>MiCirql</span><h1>Your websites</h1><p>Create, manage and publish every site from one workspace.</p></div><button onClick={()=>void create()}>+ New website</button></header>{error?<div className={styles.error}>{error}</div>:null}{loading?<div className={styles.empty}>Loading projects…</div>:projects.length?<section className={styles.grid}>{projects.map(p=><article className={styles.card} key={p.id}><div className={styles.preview}><span>{p.name.slice(0,1).toUpperCase()}</span></div><div className={styles.body}><div className={styles.top}><h2>{p.name}</h2><span className={p.published_version_id?styles.live:styles.draft}>{p.published_version_id?"Published":"Draft"}</span></div><p>{p.hostname?.hostname??"No custom domain"}{p.hostname?` · ${p.hostname.status}`:""}</p><small>Updated {new Date(p.updated_at).toLocaleDateString()} · rev {p.draft?.revision??0}</small><div className={styles.actions}><button onClick={()=>setOpen(p)}>Open editor</button><button onClick={()=>void rename(p)}>Rename</button><button onClick={()=>void duplicate(p)}>Duplicate</button><button onClick={()=>void archive(p)}>Archive</button></div></div></article>)}</section>:<div className={styles.empty}><h2>No websites yet</h2><p>Create your first website to start the business discovery flow.</p><button onClick={()=>void create()}>Create website</button></div>}</main>
}
