"use client";
import { useEffect,useState } from "react";
import type { SupabaseSession } from "./auth-client";
import styles from "./recharge-credits.module.css";

type CreditPackage={id:string;name:string;credits:number;priceInr:number;description:string};
type WalletResponse={balance:number;transactions:Array<{id:string;kind:string;credits:number;description?:string|null;created_at:string}>};
type RazorpaySuccess={razorpay_payment_id:string;razorpay_order_id:string;razorpay_signature:string};
type RazorpayCtor=new(options:{key:string;amount:number;currency:string;name:string;description:string;order_id:string;prefill?:{email?:string};handler:(response:RazorpaySuccess)=>void;modal?:{ondismiss?:()=>void}})=>{open:()=>void};

export function RechargeCredits({session,workspaceId}:{session:SupabaseSession;workspaceId:string}){
 const [open,setOpen]=useState(false),[balance,setBalance]=useState<number|null>(null),[packages,setPackages]=useState<CreditPackage[]>([]),[selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(false),[paying,setPaying]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const authHeaders={Authorization:`Bearer ${session.access_token}`};
 async function load(){setLoading(true);setError("");try{const [walletResponse,packageResponse]=await Promise.all([fetch(`/api/credits?workspaceId=${encodeURIComponent(workspaceId)}`,{headers:authHeaders,cache:"no-store"}),fetch("/api/credits/packages",{cache:"no-store"})]);const wallet=await walletResponse.json() as WalletResponse&{error?:string};const packageData=await packageResponse.json() as{packages?:CreditPackage[];error?:string};if(!walletResponse.ok)throw new Error(wallet.error??"Could not load credits.");if(!packageResponse.ok)throw new Error(packageData.error??"Could not load recharge packages.");setBalance(wallet.balance);setPackages(packageData.packages??[]);setSelected(current=>current??packageData.packages?.[1]?.id??packageData.packages?.[0]?.id??null)}catch(e){setError(e instanceof Error?e.message:"Could not load credits.")}finally{setLoading(false)}}
 useEffect(()=>{if(open)void load()},[open,workspaceId,session.access_token]);
 const chosen=packages.find(item=>item.id===selected)??null;
 async function checkout(){if(!chosen||paying)return;setPaying(true);setError("");setNotice("");try{await loadRazorpay();const orderResponse=await fetch("/api/credits/checkout/razorpay",{method:"POST",headers:{...authHeaders,"content-type":"application/json"},body:JSON.stringify({workspaceId,packageId:chosen.id})});const order=await orderResponse.json() as{keyId?:string;orderId?:string;amount?:number;currency?:string;error?:string;package?:CreditPackage};if(!orderResponse.ok||!order.keyId||!order.orderId||!order.amount||!order.currency)throw new Error(order.error??"Could not start payment.");const Razorpay=(window as unknown as{Razorpay?:RazorpayCtor}).Razorpay;if(!Razorpay)throw new Error("Razorpay checkout did not load.");const checkout=new Razorpay({key:order.keyId,amount:order.amount,currency:order.currency,name:"MiCirql",description:`${order.package?.credits??chosen.credits} credit recharge`,order_id:order.orderId,prefill:{email:session.user.email},modal:{ondismiss:()=>setPaying(false)},handler:response=>void verifyPayment(response)});checkout.open()}catch(e){setPaying(false);setError(e instanceof Error?e.message:"Could not start payment.")}}
 async function verifyPayment(payment:RazorpaySuccess){try{const response=await fetch("/api/credits/checkout/razorpay/verify",{method:"POST",headers:{...authHeaders,"content-type":"application/json"},body:JSON.stringify({workspaceId,...payment})});const result=await response.json() as{ok?:boolean;balance?:number|null;creditsAdded?:number;error?:string};if(!response.ok||!result.ok)throw new Error(result.error??"Payment verification failed.");if(typeof result.balance==="number")setBalance(result.balance);else await load();setNotice(`${result.creditsAdded??chosen?.credits??0} credits added successfully.`)}catch(e){setError(e instanceof Error?e.message:"Payment verification failed.")}finally{setPaying(false)}}
 return <><button type="button" onClick={()=>setOpen(true)}>Credits{balance!==null?` · ${balance}`:""}</button>{open?<div className={styles.backdrop} role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target&&!paying)setOpen(false)}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="recharge-title"><div className={styles.head}><div><span>Workspace credits</span><h2 id="recharge-title">Recharge MiCirql</h2><p>Use credits only when AI creates or regenerates something. Editing and previewing stay free.</p></div><button className={styles.close} aria-label="Close recharge" disabled={paying} onClick={()=>setOpen(false)}>×</button></div><div className={styles.balance}><small>Available balance</small><strong>{balance===null?"—":balance}</strong><span>credits</span></div>{error?<div className={styles.notice}>{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}{loading?<div className={styles.loading}>Loading recharge options…</div>:<div className={styles.packages}>{packages.map(pkg=><button key={pkg.id} type="button" disabled={paying} className={`${styles.package} ${selected===pkg.id?styles.selected:""}`} onClick={()=>setSelected(pkg.id)}><div><strong>{pkg.name}</strong><span>{pkg.credits} credits</span></div><b>₹{pkg.priceInr}</b><p>{pkg.description}</p></button>)}</div>}<div className={styles.footer}><div>{chosen?<><strong>{chosen.credits} credits</strong><span> for ₹{chosen.priceInr}</span></>:<span>Select a package</span>}</div><button className={styles.pay} type="button" disabled={!chosen||loading||paying} onClick={()=>void checkout()}>{paying?"Opening payment…":"Continue to payment"}</button></div></section></div>:null}</>;
}

let razorpayLoader:Promise<void>|null=null;
function loadRazorpay(){if((window as unknown as{Razorpay?:RazorpayCtor}).Razorpay)return Promise.resolve();if(razorpayLoader)return razorpayLoader;razorpayLoader=new Promise((resolve,reject)=>{const existing=document.querySelector<HTMLScriptElement>('script[src="https://checkout.razorpay.com/v1/checkout.js"]');if(existing){existing.addEventListener("load",()=>resolve(),{once:true});existing.addEventListener("error",()=>reject(new Error("Could not load Razorpay checkout.")),{once:true});return}const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";script.async=true;script.onload=()=>resolve();script.onerror=()=>reject(new Error("Could not load Razorpay checkout."));document.head.appendChild(script)});return razorpayLoader;}
