"use client";
import { useEffect,useState } from "react";
import type { SupabaseSession } from "./auth-client";
import styles from "./recharge-credits.module.css";

type CreditPackage={id:string;name:string;credits:number;priceInr:number;description:string};
type WalletResponse={balance:number;transactions:Array<{id:string;kind:string;credits:number;description?:string|null;created_at:string}>};

export function RechargeCredits({session,workspaceId}:{session:SupabaseSession;workspaceId:string}){
 const [open,setOpen]=useState(false),[balance,setBalance]=useState<number|null>(null),[packages,setPackages]=useState<CreditPackage[]>([]),[selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const authHeaders={Authorization:`Bearer ${session.access_token}`};
 async function load(){setLoading(true);setError("");try{const [walletResponse,packageResponse]=await Promise.all([fetch(`/api/credits?workspaceId=${encodeURIComponent(workspaceId)}`,{headers:authHeaders,cache:"no-store"}),fetch("/api/credits/packages",{cache:"no-store"})]);const wallet=await walletResponse.json() as WalletResponse&{error?:string};const packageData=await packageResponse.json() as{packages?:CreditPackage[];error?:string};if(!walletResponse.ok)throw new Error(wallet.error??"Could not load credits.");if(!packageResponse.ok)throw new Error(packageData.error??"Could not load recharge packages.");setBalance(wallet.balance);setPackages(packageData.packages??[]);setSelected(current=>current??packageData.packages?.[1]?.id??packageData.packages?.[0]?.id??null)}catch(e){setError(e instanceof Error?e.message:"Could not load credits.")}finally{setLoading(false)}}
 useEffect(()=>{if(open)void load()},[open,workspaceId,session.access_token]);
 const chosen=packages.find(item=>item.id===selected)??null;
 function checkout(){if(!chosen)return;window.dispatchEvent(new CustomEvent("micirql:credit-checkout",{detail:{workspaceId,packageId:chosen.id,credits:chosen.credits,priceInr:chosen.priceInr}}));setError("Payment gateway connection is the next setup step. Your selected package is ready for checkout.");}
 return <><button type="button" onClick={()=>setOpen(true)}>Credits{balance!==null?` · ${balance}`:""}</button>{open?<div className={styles.backdrop} role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)setOpen(false)}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="recharge-title"><div className={styles.head}><div><span>Workspace credits</span><h2 id="recharge-title">Recharge MiCirql</h2><p>Use credits only when AI creates or regenerates something. Editing and previewing stay free.</p></div><button className={styles.close} aria-label="Close recharge" onClick={()=>setOpen(false)}>×</button></div><div className={styles.balance}><small>Available balance</small><strong>{balance===null?"—":balance}</strong><span>credits</span></div>{error?<div className={styles.notice}>{error}</div>:null}{loading?<div className={styles.loading}>Loading recharge options…</div>:<div className={styles.packages}>{packages.map(pkg=><button key={pkg.id} type="button" className={`${styles.package} ${selected===pkg.id?styles.selected:""}`} onClick={()=>setSelected(pkg.id)}><div><strong>{pkg.name}</strong><span>{pkg.credits} credits</span></div><b>₹{pkg.priceInr}</b><p>{pkg.description}</p></button>)}</div>}<div className={styles.footer}><div>{chosen?<><strong>{chosen.credits} credits</strong><span> for ₹{chosen.priceInr}</span></>:<span>Select a package</span>}</div><button className={styles.pay} type="button" disabled={!chosen||loading} onClick={checkout}>Continue to payment</button></div></section></div>:null}</>;
}
