import type { BackendImplementationContract, BackendPolicy, BackendTable } from "@micirql/schema";

export type SupabaseMigrationArtifact = {
  sql: string;
  tableCount: number;
  policyCount: number;
  bucketCount: number;
  warnings: string[];
};

const IDENTIFIER = /^[a-z_][a-z0-9_]*$/;
const POLICY_NAME = /^[a-z0-9_-]+$/;
const SAFE_DEFAULT = /^(?:gen_random_uuid\(\)|now\(\)|auth\.uid\(\)|true|false|-?\d+(?:\.\d+)?|'[^'\\]*(?:\\.[^'\\]*)*')$/i;
const SAFE_POLICY = /^[a-z0-9_().'\s=><!,:\-]+$/i;

export function generateSupabaseMigration(contract: BackendImplementationContract): SupabaseMigrationArtifact {
  if (contract.provider !== "supabase") throw new Error("SUPABASE_MIGRATION_PROVIDER_REQUIRED");

  const warnings: string[] = [];
  const statements: string[] = [
    "-- Generated by MiCirql Backend Implementation Engine.",
    "-- Review in a preview/staging Supabase project before production apply.",
    "begin;",
    "create extension if not exists pgcrypto;",
  ];

  const knownTables = new Set(contract.tables.map((table) => table.name));
  for (const table of contract.tables) {
    validateTable(table, knownTables);
    statements.push(renderTable(table));
    for (const index of table.indexes) statements.push(renderIndex(table.name, index));
    if (table.rlsEnabled) statements.push(`alter table public.${q(table.name)} enable row level security;`);
  }

  for (const policy of contract.policies) {
    if (!knownTables.has(policy.table)) throw new Error(`BACKEND_POLICY_TABLE_MISSING:${policy.id}:${policy.table}`);
    statements.push(renderPolicy(policy));
  }

  for (const bucket of contract.storageBuckets) {
    assertIdentifier(bucket.id.replace(/-/g, "_"), `storage bucket ${bucket.id}`);
    const mime = bucket.allowedMimePrefixes.length
      ? `array[${bucket.allowedMimePrefixes.map((value) => sqlString(value)).join(", ")}]::text[]`
      : "null";
    const maxBytes = bucket.maxBytes ?? "null";
    statements.push(
      `insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values (${sqlString(bucket.id)}, ${sqlString(bucket.id)}, ${bucket.public ? "true" : "false"}, ${maxBytes}, ${mime}) on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;`,
    );
    if (bucket.ownerScoped) warnings.push(`Storage bucket ${bucket.id} requires runtime ownership-path enforcement in addition to database policies.`);
  }

  statements.push("commit;");
  return {
    sql: statements.join("\n\n") + "\n",
    tableCount: contract.tables.length,
    policyCount: contract.policies.length,
    bucketCount: contract.storageBuckets.length,
    warnings,
  };
}

function renderTable(table: BackendTable) {
  const columns = table.columns.map((column) => {
    assertIdentifier(column.name, `column ${table.name}.${column.name}`);
    const parts = [q(column.name), sqlType(column.type)];
    if (!column.nullable) parts.push("not null");
    if (column.defaultSql) {
      if (!SAFE_DEFAULT.test(column.defaultSql.trim())) throw new Error(`UNSAFE_COLUMN_DEFAULT:${table.name}.${column.name}`);
      parts.push(`default ${column.defaultSql.trim()}`);
    }
    if (column.unique) parts.push("unique");
    if (column.references) parts.push(`references public.${renderReference(column.references)}`);
    return parts.join(" ");
  });
  assertIdentifier(table.primaryKey, `primary key ${table.name}`);
  columns.push(`primary key (${q(table.primaryKey)})`);
  return `create table if not exists public.${q(table.name)} (\n  ${columns.join(",\n  ")}\n);`;
}

function renderIndex(table: string, columns: string[]) {
  if (!columns.length) throw new Error(`EMPTY_INDEX:${table}`);
  columns.forEach((column) => assertIdentifier(column, `index ${table}.${column}`));
  const indexName = `${table}_${columns.join("_")}_idx`;
  assertIdentifier(indexName, `index ${indexName}`);
  return `create index if not exists ${q(indexName)} on public.${q(table)} (${columns.map(q).join(", ")});`;
}

function renderPolicy(policy: BackendPolicy) {
  if (!POLICY_NAME.test(policy.id)) throw new Error(`UNSAFE_POLICY_NAME:${policy.id}`);
  const operation = policy.operation.toUpperCase();
  const usingSql = safePolicySql(policy.usingSql, policy.id, "using");
  const checkSql = safePolicySql(policy.checkSql, policy.id, "check");
  const clauses = [
    `create policy ${quotePolicyName(policy.id)} on public.${q(policy.table)}`,
    `for ${operation}`,
    "to authenticated",
    ...(usingSql ? [`using (${usingSql})`] : []),
    ...(checkSql ? [`with check (${checkSql})`] : []),
  ];
  return `${clauses.join("\n  ")};`;
}

function validateTable(table: BackendTable, knownTables: Set<string>) {
  assertIdentifier(table.name, `table ${table.name}`);
  const names = new Set<string>();
  for (const column of table.columns) {
    if (names.has(column.name)) throw new Error(`DUPLICATE_COLUMN:${table.name}.${column.name}`);
    names.add(column.name);
    if (column.references) {
      const parsed = parseReference(column.references);
      if (!knownTables.has(parsed.table)) throw new Error(`REFERENCE_TABLE_MISSING:${table.name}.${column.name}:${parsed.table}`);
    }
  }
  if (!names.has(table.primaryKey)) throw new Error(`PRIMARY_KEY_COLUMN_MISSING:${table.name}.${table.primaryKey}`);
  for (const index of table.indexes) for (const column of index) if (!names.has(column)) throw new Error(`INDEX_COLUMN_MISSING:${table.name}.${column}`);
}

function renderReference(value: string) {
  const parsed = parseReference(value);
  return `${q(parsed.table)}(${q(parsed.column)})`;
}

function parseReference(value: string) {
  const match = /^([a-z_][a-z0-9_]*)\(([a-z_][a-z0-9_]*)\)$/.exec(value.trim());
  if (!match) throw new Error(`UNSAFE_REFERENCE:${value}`);
  return { table: match[1]!, column: match[2]! };
}

function safePolicySql(value: string | undefined, id: string, kind: string) {
  if (!value) return undefined;
  const sql = value.trim();
  if (!sql || !SAFE_POLICY.test(sql) || /;|--|\/\*/.test(sql)) throw new Error(`UNSAFE_POLICY_SQL:${id}:${kind}`);
  return sql;
}

function sqlType(type: BackendTable["columns"][number]["type"]) {
  if (type === "integer") return "integer";
  if (type === "numeric") return "numeric";
  if (type === "boolean") return "boolean";
  if (type === "date") return "date";
  if (type === "timestamptz") return "timestamptz";
  if (type === "uuid") return "uuid";
  if (type === "jsonb") return "jsonb";
  return "text";
}

function assertIdentifier(value: string, context: string) {
  if (!IDENTIFIER.test(value)) throw new Error(`UNSAFE_SQL_IDENTIFIER:${context}`);
}
function q(value: string) { assertIdentifier(value, value); return `"${value}"`; }
function quotePolicyName(value: string) { return `"${value}"`; }
function sqlString(value: string) { return `'${value.replace(/'/g, "''")}'`; }
