"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { SCHEMA_VERSION,siteSchema,type Site } from "@micirql/schema";
import { FAMILY_CODES,SECTION_FAMILIES,type SectionFamily } from "@micirql/sections";
import { createEditorHistory,createEditorState,executeEditorCommand,markEditorSaved,redoEditor,setEditorSelection,setEditorViewport,undoEditor,type EditorHistory,type EditorViewport } from "@micirql/workspace";
import { RendererPreview } from "./renderer-preview";
import { SectionDesignSwitcher } from "./section-design-switcher";
import { AssetPicker } from "./asset-picker";
import { PagesManager } from "./pages-manager";
import { FunctionsManager } from "./functions-manager";
import { PublishReadinessManager,publishReadiness } from "./publish-readiness";
import { PublishController } from "./publish-controller";

type Mode="content"|"images"|"design"|"pages"|"seo"|"functions"|"domain";
type SaveState="loading"|"saved"|"unsaved"|"saving"|"conflict"|"error";
type DraftApiRecord={workspaceId:string;siteId:string;revision:number;snapshot:Site;updatedAt:string;updatedBy:string};
const initialSite:Site={schemaVersion:SCHEMA_VERSION,siteId:"workspace-preview",workspaceId:"workspace-demo",name:"Your website",domain:"landing-page",theme:{family:"minimalist",modifiers:["light"],brand:{colors:{primary:"#6d5dfc",secondary:"#171717",accent:"#8b7fff",background:"#ffffff",surface:"#f5f5f7",textPrimary:"#111111",textSecondary:"#65656b",border:"#dddde3",success:"#168a4a",warning:"#ad6a00",error:"#c93636"},typography:{display:"Arial",body:"Arial",ui:"Arial"},density:"comfortable",shape:"balanced",motion:"subtle"}},seoBlueprint:{primaryGoal:"Present the business clearly and convert visitors",targetLocations:[],priorityTopics:[],audiences:[],languages:["en"],localSeo:false,servicePages:true,locationPages:false,blog:false},pages:[{id:"home",path:"/",name:"Home",sections:[{id:"hero-1",component:{componentId:"hero.placeholder",version:"1.0.0"},props:{eyebrow:"Built with MiCirql",heading:"A website your business can grow into.",body:"Select any section to edit its content, images, design and actions without touching code."},bindings:{},hidden:false},{id:"features-1",component:{componentId:"features.placeholder",version:"1.0.0"},props:{heading:"Everything stays editable",body:"The live draft is a validated Site Schema. Changes update the preview immediately and remain safe to publish.",items:[{title:"Mobile first",description:"Every layout begins with the smallest screen."},{title:"Fast by default",description:"Approved components stay within the MiCirql performance protocol."},{title:"Fully editable",description:"Content, assets, design and functionality remain workspace-controlled."}]},bindings:{},hidden:false}],seo:{title:"Your website",description:"A website created with MiCirql.",canonicalPath:"/",indexable:true,structuredDataTypes:[]}}],navigation:[{label:"Home",href:"/"}],integrations:[],domains:[]};

export default function WorkspaceClient(){
 const [history,setHistory]=useState<EditorHistory>(()=>createEditorHistory(createEditorState(initialSite))); const [mode,setMode]=useState<Mode>("content"); const [saveState,setSaveState]=useState<SaveState>("loading"); const [persistedRevision,setPersistedRevision]=useState(0); const [conflictDraft,setConflictDraft]=useState<DraftApiRecord>(); const loaded=useRef(false);
 const state=history.present; const selection=state.selected; const selectedPageId=selection.kind==="page"||selection.kind==="section"?selection.pageId:undefined; const selectedSectionId=selection.kind==="section"?selection.sectionId:undefined; const activePage=useMemo(()=>selectedPageId?state.site.pages.find(p=>p.id===selectedPageId)??state.site.pages[0]!:state.site.pages[0]!,[state.site.pages,selectedPageId]); const activeSection=selectedSectionId?activePage.sections.find(s=>s.id===selectedSectionId):undefined; const activeSectionFamily=activeSection?sectionFamilyFromComponentId(activeSection.component.componentId):undefined; const readiness=publishReadiness(state.site); const currentAssetId=activeSection&&typeof activeSection.props.image==="object"&&activeSection.props.image!==null&&!Array.isArray(activeSection.props.image)?String((activeSection.props.image as Record<string,unknown>).assetId??"")||undefined:undefined;
 useEffect(()=>{let cancelled=false;(async()=>{try{const q=new URLSearchParams({workspaceId:initialSite.workspaceId,siteId:initialSite.siteId});const r=await fetch(`/api/drafts?${q}`,{cache:"no-store"});if(cancelled)return;if(r.status===404){setSaveState("saved");loaded.current=true;return}if(!r.ok)throw new Error(`Draft load failed (${r.status}).`);const p=await r.json() as {draft:DraftApiRecord};const site=siteSchema.parse(p.draft.snapshot);const editor=createEditorState(site);editor.revision=p.draft.revision;setHistory(createEditorHistory(editor));setPersistedRevision(p.draft.revision);setSaveState("saved");loaded.current=true}catch(e){if(!cancelled){console.error(e);setSaveState("error");loaded.current=true}}})();return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!loaded.current||!state.dirty||saveState==="saving"||saveState==="conflict")return;const t=window.setTimeout(()=>void persist(state.site,state.revision),700);return()=>window.clearTimeout(t)},[state.site,state.revision,state.dirty,persistedRevision,saveState]);
 function commit(command:Parameters<typeof executeEditorCommand>[1]){try{setHistory(c=>executeEditorCommand(c,command));setSaveState("unsaved")}catch(e){window.alert(e instanceof Error?e.message:"This change is not allowed.")}}
 function selectPage(pageId:string){setHistory(c=>({...c,present:setEditorSelection(c.present,{kind:"page",pageId})}))} function selectSection(pageId:string,sectionId:string){setHistory(c=>({...c,present:setEditorSelection(c.present,{kind:"section",pageId,sectionId})}))} function setViewport(viewport:EditorViewport){setHistory(c=>({...c,present:setEditorViewport(c.present,viewport)}))}
 async function persist(snapshot:Site,sentEditorRevision:number):Promise<boolean>{if(saveState==="conflict")return false;if(saveState==="saving")return false;setSaveState("saving");try{const r=await fetch("/api/drafts",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({snapshot,expectedRevision:persistedRevision,updatedBy:"workspace-user"})});const p=await r.json() as {draft?:DraftApiRecord;error?:string};if(r.status===409){setConflictDraft(p.draft);setSaveState("conflict");return false}if(!r.ok||!p.draft)throw new Error(p.error??`Draft save failed (${r.status}).`);setPersistedRevision(p.draft.revision);setHistory(c=>({...c,present:c.present.revision===sentEditorRevision?markEditorSaved(c.present):c.present}));setSaveState(c=>c==="conflict"?c:"saved");return true}catch(e){console.error(e);setSaveState("error");return false}}
 async function ensureSaved(){if(!state.dirty&&saveState==="saved")return true;return persist(state.site,state.revision)}
 function loadServerVersion(){if(!conflictDraft)return;const site=siteSchema.parse(conflictDraft.snapshot);const editor=createEditorState(site);editor.revision=conflictDraft.revision;setHistory(createEditorHistory(editor));setPersistedRevision(conflictDraft.revision);setConflictDraft(undefined);setSaveState("saved")}
 return <main className="workspace-shell">
 <header className="workspace-topbar"><div className="brand-lockup"><strong>MiCirql</strong><span>{state.site.name}</span></div><div className="page-switcher">{state.site.pages.map(p=><button key={p.id} className={p.id===activePage.id?"is-active":""} onClick={()=>selectPage(p.id)}>{p.name}</button>)}</div><div className="workspace-actions"><span className={`save-state ${saveState}`}>{saveLabel(saveState)}</span><button onClick={()=>{setHistory(c=>undoEditor(c));setSaveState("unsaved")}} disabled={!history.past.length}>Undo</button><button onClick={()=>{setHistory(c=>redoEditor(c));setSaveState("unsaved")}} disabled={!history.future.length}>Redo</button><button onClick={()=>void persist(state.site,state.revision)} disabled={saveState==="saving"||saveState==="loading"}>Save</button><PublishController site={state.site} disabled={!readiness.ready||saveState==="loading"||saveState==="conflict"} ensureSaved={ensureSaved}/></div></header>
 {saveState==="conflict"?<section className="draft-conflict" role="alert"><div><strong>This draft changed elsewhere.</strong><span>Your local edits were not overwritten.</span></div><button onClick={loadServerVersion}>Load latest saved version</button></section>:null}
 <aside className="workspace-rail">{(["content","images","design","pages","seo","functions","domain"] as Mode[]).map(item=><button key={item} className={mode===item?"is-active":""} onClick={()=>setMode(item)}>{item}</button>)}</aside>
 <section className="workspace-canvas"><div className="viewport-switcher">{(["mobile","tablet","desktop"] as EditorViewport[]).map(v=><button key={v} className={state.viewport===v?"is-active":""} onClick={()=>setViewport(v)}>{v}</button>)}</div><RendererPreview site={state.site} path={activePage.path} viewport={state.viewport} {...(activeSection?{selectedSectionId:activeSection.id}:{})} onSelectSection={id=>selectSection(activePage.id,id)}/></section>
 <aside className="workspace-inspector"><div className="inspector-heading"><span>{mode}</span><strong>{activeSection?activeSection.id:activePage.name}</strong></div>
 {mode==="content"&&activeSection?<div className="inspector-form"><label>Heading<input value={String(activeSection.props.heading??activeSection.props.title??"")} onChange={e=>commit({type:"content.set",pageId:activePage.id,sectionId:activeSection.id,propPath:activeSection.props.title!==undefined?"title":"heading",value:e.target.value})}/></label><label>Body<textarea value={String(activeSection.props.body??activeSection.props.description??"")} onChange={e=>commit({type:"content.set",pageId:activePage.id,sectionId:activeSection.id,propPath:activeSection.props.description!==undefined?"description":"body",value:e.target.value})}/></label></div>
 :mode==="images"&&activeSection&&activeSectionFamily?<AssetPicker workspaceId={state.site.workspaceId} siteId={state.site.siteId} pagePath={activePage.path} sectionId={activeSection.id} domain={state.site.domain} theme={state.site.theme.family} family={activeSectionFamily} {...(currentAssetId?{currentAssetId}:{})} onSelect={(asset,o)=>commit({type:"asset.set",pageId:activePage.id,sectionId:activeSection.id,propPath:"image",asset:{assetId:asset.id,alt:o?.alt??asset.alt,focalPoint:o?.focalPoint??asset.focalPoint}})}/>
 :mode==="pages"?<PagesManager site={state.site} activePageId={activePage.id} onSelect={selectPage} onAdd={p=>{commit({type:"page.add",page:p});selectPage(p.id)}} onRemove={id=>{commit({type:"page.remove",pageId:id});if(id===activePage.id)selectPage(state.site.pages[0]!.id)}} onDuplicate={p=>{commit({type:"page.add",page:p});selectPage(p.id)}} onPathChange={(id,path)=>commit({type:"page.path.set",pageId:id,path})} onReorder={(id,toIndex)=>commit({type:"page.reorder",pageId:id,toIndex})}/>
 :mode==="functions"&&activeSection?<FunctionsManager site={state.site} section={activeSection} onBind={(bindingKey,actionId)=>commit({type:"binding.set",pageId:activePage.id,sectionId:activeSection.id,bindingKey,actionId})} onRemove={bindingKey=>commit({type:"binding.remove",pageId:activePage.id,sectionId:activeSection.id,bindingKey})}/>
 :mode==="domain"?<PublishReadinessManager site={state.site}/>
 :mode==="seo"?<div className="inspector-form"><label>SEO title<input value={activePage.seo.title} onChange={e=>commit({type:"page.seo.patch",pageId:activePage.id,patch:{title:e.target.value}})}/></label><label>Description<textarea value={activePage.seo.description} onChange={e=>commit({type:"page.seo.patch",pageId:activePage.id,patch:{description:e.target.value}})}/></label></div>
 :mode==="design"?<div className="inspector-form"><label>Primary color<input type="color" value={state.site.theme.brand.colors.primary} onChange={e=>commit({type:"brand.patch",patch:{colors:{...state.site.theme.brand.colors,primary:e.target.value}}})}/></label><label>Background<input type="color" value={state.site.theme.brand.colors.background} onChange={e=>commit({type:"brand.patch",patch:{colors:{...state.site.theme.brand.colors,background:e.target.value}}})}/></label>{activeSection&&activeSectionFamily?<SectionDesignSwitcher family={activeSectionFamily} theme={state.site.theme.family} currentComponentId={activeSection.component.componentId} onSelect={(componentId,version)=>commit({type:"section.component.set",pageId:activePage.id,sectionId:activeSection.id,componentId,version})}/>:null}</div>
 :<div className="inspector-empty"><p>Select a section to configure this area.</p></div>}</aside>
 <nav className="mobile-editor-bar">{(["content","images","design","pages","seo","functions","domain"] as Mode[]).map(item=><button key={item} className={mode===item?"is-active":""} onClick={()=>setMode(item)}>{item}</button>)}</nav>
 </main>;
}
function sectionFamilyFromComponentId(componentId:string):SectionFamily|undefined{const n=componentId.toLowerCase();const legacy=SECTION_FAMILIES.find(f=>n===`${f}.placeholder`||n.startsWith(`${f}.`));if(legacy)return legacy;const u=componentId.toUpperCase();return SECTION_FAMILIES.find(f=>u.includes(`-${FAMILY_CODES[f]}-`))}
function saveLabel(s:SaveState){return s==="loading"?"Loading…":s==="saving"?"Saving…":s==="unsaved"?"Unsaved":s==="conflict"?"Conflict":s==="error"?"Save error":"Saved"}