import { NextRequest, NextResponse } from "next/server";
import { siteSchema } from "@micirql/schema";
import { buildContentEnrichmentContract, enforceContentEnrichmentIntegrity, groundSiteContent, industryPlannerContext } from "@micirql/design-engine";
import { composeWebsite } from "../../composition-intelligence";
import { inferGenerationQuality } from "../../generation-quality-intelligence";
import { planVisualMedia } from "../../visual-media-intelligence";
import { executeMediaPlan } from "../../media-execution";
import { materializeGeneratedMedia } from "../../materialize-media-execution";
import { applyMediaExecution } from "../../apply-media-execution";
import { applyComposition } from "../../apply-composition";
import { applyPremiumQualityCorrection } from "../../premium-quality-correction";
import { lockProjectBrief, mergeAiPlanningAdvice } from "../../project-brief-guard";
import { getSupabaseDraft, saveSupabaseDraft } from "../drafts/supabase-store";
import { creditsForWebsiteGeneration, getCreditBalance, grantTrialCredits, refundCredits, reserveCredits } from "../credits/supabase-credit-runtime";
import { loadMediaPools } from "./media-assets";
import { generateAndUploadSocialCard } from "./social-card";

function config(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error("Supabase configuration is missing.");return{url,key};}
function auth(request:NextRequest){const authorization=request.headers.get("authorization");if(!authorization?.startsWith("Bearer ")){const error=new Error("AUTH_REQUIRED") as Error&{status?:number};error.status=401;throw error;}return authorization;}
function headers(request:NextRequest){const{key}=config();return{apikey:key,authorization:auth(request),"content-type":"application/json"};}

export async function GET(request:NextRequest){try{const workspaceId=request.nextUrl.searchParams.get("workspaceId")?.trim(),siteId=request.nextUrl.searchParams.get("siteId")?.trim();if(!workspaceId||!siteId)return NextResponse.json({error:"workspaceId and siteId are required"},{status:400});const{url}=config();const query=new URLSearchParams({workspace_id:`eq.${workspaceId}`,site_id:`eq.${siteId}`,select:"*",limit:"1"});const response=await fetch(`${url}/rest/v1/business_onboarding_profiles?${query}`,{headers:headers(request),cache:"no-store"});if(!response.ok)throw await remoteError(response);const rows=await response.json() as unknown[];return NextResponse.json({completed:Boolean((rows[0] as any)?.completed_at),profile:rows[0]??null});}catch(error){return errorResponse(error);}}

export async function POST(request:NextRequest){
 let reservation:{workspaceId:string;credits:number;operationKey:string}|null=null;
 try{
  const body=await request.json() as Record<string,unknown>;
  const workspaceId=string(body.workspaceId),siteId=string(body.siteId),businessName=string(body.businessName),industry=string(body.industry);
  if(!workspaceId||!siteId||!businessName||!industry)return NextResponse.json({error:"workspaceId, siteId, businessName and industry are required"},{status:400});
  const authorization=auth(request);const{url,key}=config();const commonHeaders={apikey:key,authorization,"content-type":"application/json"};
  const userResponse=await fetch(`${url}/auth/v1/user`,{headers:commonHeaders,cache:"no-store"});if(!userResponse.ok)throw await remoteError(userResponse);const user=await userResponse.json() as{id?:string};if(!user.id)throw new Error("Authenticated user could not be resolved.");
  await grantTrialCredits(workspaceId);
  const websiteCredits=creditsForWebsiteGeneration();
  const operationKey=`generate-website:${siteId}:${crypto.randomUUID()}`;
  await reserveCredits({workspaceId,credits:websiteCredits,operationKey,description:"AI website generation",metadata:{siteId,businessName,industry}});
  reservation={workspaceId,credits:websiteCredits,operationKey};
  const services=stringArray(body.services),goals=stringArray(body.goals),styleTags=stringArray(body.styleTags),requiredCapabilities=stringArray(body.requiredCapabilities),languageValues=stringArray(body.languages),languages=languageValues.length?languageValues:["en"],subindustry=optionalString(body.subindustry),location=optionalString(body.location),notes=optionalString(body.notes),logoUrl=optionalString(body.logoUrl),brandColors=hexArray(body.brandColors);
  const lockedBrief=lockProjectBrief({workspaceId,siteId,businessName,industry,subindustry,location,services});
  const industryContext=industryPlannerContext(lockedBrief.industry,lockedBrief.subindustry??undefined);
  const aiResponse=await fetch(`${url}/functions/v1/ai-plan-site`,{method:"POST",headers:commonHeaders,body:JSON.stringify({workspace_id:lockedBrief.workspaceId,site_id:lockedBrief.siteId,business_name:lockedBrief.businessName,industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,location:lockedBrief.location,services:lockedBrief.services,goals,style_tags:styleTags,required_capabilities:requiredCapabilities,languages,notes,brand_colors:brandColors,industry_context:industryContext})});if(!aiResponse.ok)throw await remoteError(aiResponse);
  const rawAdvice=await aiResponse.json() as any;const advice=mergeAiPlanningAdvice(lockedBrief,rawAdvice);
  const requestPayload={workspace_id:lockedBrief.workspaceId,site_id:lockedBrief.siteId,industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,style_tags:advice.styleTags,required_capabilities:advice.requiredCapabilities,goals:advice.goals,industry_context:industryContext};
  const planResponse=await fetch(`${url}/functions/v1/plan-site`,{method:"POST",headers:commonHeaders,body:JSON.stringify(requestPayload)});if(!planResponse.ok)throw await remoteError(planResponse);
  const plan=await planResponse.json() as{plan_id?:string;blueprint?:unknown;selected_layout?:{id?:unknown;name?:unknown;score?:unknown;reasons?:unknown}};if(!plan.plan_id)throw new Error("Planner did not return a plan ID.");
  const plannerLayoutId=string(plan.selected_layout?.id),plannerCandidates=(industryContext as{certifiedLayoutCandidates?:unknown[]}|undefined)?.certifiedLayoutCandidates??[];
  if(plannerCandidates.length&&!plannerLayoutId)throw new Error("Planner did not return a certified layout selection.");
  const buildResponse=await fetch(`${url}/functions/v1/build-site`,{method:"POST",headers:commonHeaders,body:JSON.stringify({plan_id:plan.plan_id,site_id:lockedBrief.siteId})});if(!buildResponse.ok)throw await remoteError(buildResponse);
  const buildPayload=await buildResponse.json() as{build?:any},build=buildPayload.build,buildId=typeof build==="object"&&build?(build.id??build.build_id??null):null,brief={businessName:lockedBrief.businessName,industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,location:lockedBrief.location,services:lockedBrief.services,goals,styleTags,requiredCapabilities,languages,notes,logoUrl,brandColors:advice.brandColors,industryContext};
  let content:unknown=null,contentWarning:string|null=null;let contentIntegrity={checked:false,structureIntact:true,appliedFields:0,restoredChanges:[] as string[],corrected:false};let contentGrounding={checked:false,grounded:true,issueCount:0,issues:[] as Array<{pageId:string;sectionId:string;field:string;reason:string}>};
  try{const builtDraft=await getSupabaseDraft(request,lockedBrief.workspaceId,lockedBrief.siteId);if(!builtDraft)throw new Error("Generated draft could not be loaded for page-specific content enrichment.");const pageContentContract=buildContentEnrichmentContract(builtDraft.snapshot);const contentResponse=await fetch(`${url}/functions/v1/enrich-site-content`,{method:"POST",headers:commonHeaders,body:JSON.stringify({workspace_id:lockedBrief.workspaceId,site_id:lockedBrief.siteId,build_id:buildId,brief,page_content_contract:pageContentContract,content_policy:{mode:"content-only",preserve_page_paths:true,preserve_section_order:true,preserve_component_ids:true,preserve_design_props:true,preserve_media_props:true,preserve_bindings:true,forbid_unsupplied_claims:true}})});if(!contentResponse.ok)throw await remoteError(contentResponse);content=await contentResponse.json();const enrichedDraft=await getSupabaseDraft(request,lockedBrief.workspaceId,lockedBrief.siteId);if(!enrichedDraft)throw new Error("Enriched draft could not be reloaded for integrity verification.");const guarded=enforceContentEnrichmentIntegrity(builtDraft.snapshot,enrichedDraft.snapshot),grounded=groundSiteContent(guarded.site,{businessName:lockedBrief.businessName,industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,location:lockedBrief.location,services:lockedBrief.services,goals,notes}),validatedSnapshot=siteSchema.parse({...grounded.site,name:lockedBrief.businessName}),corrected=JSON.stringify(validatedSnapshot)!==JSON.stringify(enrichedDraft.snapshot);if(corrected)await saveSupabaseDraft(request,{snapshot:validatedSnapshot,expectedRevision:enrichedDraft.revision});contentIntegrity={checked:true,structureIntact:guarded.structureIntact,appliedFields:guarded.appliedFields,restoredChanges:guarded.restoredChanges,corrected};contentGrounding={checked:true,grounded:grounded.grounded,issueCount:grounded.issues.length,issues:grounded.issues.map(issue=>({pageId:issue.pageId,sectionId:issue.sectionId,field:issue.field,reason:issue.reason}))};}catch(error){contentWarning=error instanceof Error?error.message:"Content enrichment failed.";console.error("MiCirql content enrichment failed; continuing with structural draft.",error);}
  const recommendationProfile={industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,services:lockedBrief.services,goals:advice.goals,style_tags:advice.styleTags,required_capabilities:advice.requiredCapabilities};
  const plannerLayoutScore=Number(plan.selected_layout?.score),plannerLayoutReasons=stringArray(plan.selected_layout?.reasons);
  const composition=composeWebsite(recommendationProfile,plannerLayoutId?{selectedLayoutId:plannerLayoutId,selectedLayoutScore:Number.isFinite(plannerLayoutScore)?plannerLayoutScore:null,selectedLayoutReasons:plannerLayoutReasons}:undefined);
  if(plannerLayoutId&&composition.layoutCandidate?.layout.id!==plannerLayoutId)throw new Error(`Planner/composition layout drift: ${plannerLayoutId} != ${composition.layoutCandidate?.layout.id??"none"}`);
  const quality=inferGenerationQuality(recommendationProfile,composition),visualMediaPlan=planVisualMedia(recommendationProfile,composition,quality);
  let mediaExecution=null,imageWarning:string|null=null;let generatedMediaCount=0;const mediaMaterializationWarnings:string[]=[];
  try{const pools=await loadMediaPools(lockedBrief.workspaceId);mediaExecution=executeMediaPlan({plan:visualMediaPlan,...pools,allowGeneration:false});}catch(error){imageWarning=error instanceof Error?error.message:"Media execution planning failed.";console.error("MiCirql media execution failed; continuing without resolved media.",error);}
  let initialPreset:{id:string;name:string;reasons:string[]}|null=null,initialComposition:{intent:string;sections:Array<{family:string;variant:number;purpose:string;priority:string}>;reasoning:string[]}|null=null,presetWarning:string|null=null,socialCardWarning:string|null=null;let premiumQuality:ReturnType<typeof applyPremiumQualityCorrection>|null=null;
  try{const current=await getSupabaseDraft(request,lockedBrief.workspaceId,lockedBrief.siteId);if(!current)throw new Error("Generated draft could not be loaded for composition application.");let nextSnapshot=applyComposition(current.snapshot,composition,quality);if(mediaExecution){try{const materialized=await materializeGeneratedMedia({request,site:nextSnapshot,execution:mediaExecution,workspaceId:lockedBrief.workspaceId,siteId:lockedBrief.siteId,domain:lockedBrief.industry,maxGenerated:0});mediaExecution=materialized.execution;generatedMediaCount=materialized.generated;mediaMaterializationWarnings.push(...materialized.warnings);}catch(error){mediaMaterializationWarnings.push(error instanceof Error?error.message:"Generated media materialization failed.");console.error("MiCirql generated media materialization failed; continuing with resolved reusable media.",error);}nextSnapshot=applyMediaExecution(nextSnapshot,mediaExecution);}nextSnapshot=siteSchema.parse({...nextSnapshot,name:lockedBrief.businessName});const[primary,accent,secondary,surface,border]=advice.brandColors;if(primary||accent||secondary||surface||border){nextSnapshot.theme.brand.colors={...nextSnapshot.theme.brand.colors,...(primary?{primary}:{}),...(accent?{accent}:{}),...(secondary?{secondary,textPrimary:secondary}:{}),...(surface?{surface}:{}),...(border?{border}:{})};nextSnapshot=siteSchema.parse(nextSnapshot);}premiumQuality=applyPremiumQualityCorrection(nextSnapshot);nextSnapshot=premiumQuality.site;try{const socialCard=await generateAndUploadSocialCard({site:nextSnapshot,supabaseUrl:url,supabaseKey:key,authorization});nextSnapshot.theme.brand.socialImageAssetId=socialCard.url;nextSnapshot.theme.brand.socialImageStrategy="generated-card";nextSnapshot=siteSchema.parse(nextSnapshot);}catch(error){socialCardWarning=error instanceof Error?error.message:"Social share card could not be generated.";console.error("MiCirql social share card generation failed; using brand fallback.",error);if(nextSnapshot.theme.brand.logoAssetId){nextSnapshot.theme.brand.socialImageAssetId=nextSnapshot.theme.brand.logoAssetId;nextSnapshot.theme.brand.socialImageStrategy="logo-fallback";}else if(nextSnapshot.theme.brand.faviconAssetId){nextSnapshot.theme.brand.socialImageAssetId=nextSnapshot.theme.brand.faviconAssetId;nextSnapshot.theme.brand.socialImageStrategy="favicon-fallback";}}await saveSupabaseDraft(request,{snapshot:nextSnapshot,expectedRevision:current.revision});initialPreset={id:composition.preset.id,name:composition.preset.name,reasons:composition.reasoning};initialComposition={intent:composition.intent,sections:composition.sections,reasoning:composition.reasoning};}catch(error){presetWarning=error instanceof Error?error.message:"Initial composition could not be applied.";console.error("MiCirql initial composition failed; continuing with generated draft.",error);}
  const images={mode:mediaExecution?"resolved":"planned",generated:generatedMediaCount>0,generatedCount:generatedMediaCount,style:visualMediaPlan.style,sections:visualMediaPlan.sections,rules:visualMediaPlan.rules,execution:mediaExecution,materializationWarnings:mediaMaterializationWarnings};
  const profile={workspace_id:lockedBrief.workspaceId,site_id:lockedBrief.siteId,created_by:user.id,business_name:lockedBrief.businessName,industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,location:lockedBrief.location,services:lockedBrief.services,goals,style_tags:styleTags,required_capabilities:requiredCapabilities,languages,notes,logo_url:logoUrl,brand_colors:advice.brandColors,plan_id:plan.plan_id,build_id:buildId,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const profileResponse=await fetch(`${url}/rest/v1/business_onboarding_profiles?on_conflict=workspace_id,site_id`,{method:"POST",headers:{...commonHeaders,Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(profile)});if(!profileResponse.ok)throw await remoteError(profileResponse);
  const savedProfiles=await profileResponse.json() as unknown[];
  const creditBalance=await getCreditBalance(workspaceId);
  reservation=null;
  return NextResponse.json({ok:true,planId:plan.plan_id,build,blueprint:plan.blueprint,selectedLayout:plan.selected_layout??null,industryContext,planningSource:advice.source,planningProvider:advice.provider??null,planningModel:advice.model??null,planningUsage:advice.usage??null,planningWarning:advice.warning??null,brandPalette:advice.brandColors,content,contentWarning,contentIntegrity,contentGrounding,images,imageWarning,visualMediaPlan,mediaExecution,initialPreset,initialComposition,generationQuality:quality,premiumQuality:premiumQuality?{premiumReady:premiumQuality.final.premiumReady,initialScore:premiumQuality.initial.score,finalScore:premiumQuality.final.score,attemptedCorrection:premiumQuality.attempted,appliedCorrection:premiumQuality.applied,blockers:premiumQuality.final.blockers,warnings:premiumQuality.final.warnings,metrics:premiumQuality.final.metrics}:null,presetWarning,socialCardWarning,creditsCharged:websiteCredits,creditBalance,profile:savedProfiles[0]??profile});
 }catch(error){
  if(reservation){try{await refundCredits({workspaceId:reservation.workspaceId,credits:reservation.credits,operationKey:`refund:${reservation.operationKey}`,description:"Refund failed AI website generation",metadata:{reservation:reservation.operationKey}});}catch(refundError){console.error("MiCirql website credit refund failed",refundError);}}
  return errorResponse(error);
 }
}

function string(value:unknown){return typeof value==="string"?value.trim():"";}
function optionalString(value:unknown){const valueString=string(value);return valueString||null;}
function stringArray(value:unknown){if(Array.isArray(value))return value.map(string).filter(Boolean);if(typeof value==="string")return value.split(",").map(item=>item.trim()).filter(Boolean);return [];}
function hexArray(value:unknown){return stringArray(value).filter(item=>/^#[0-9a-f]{6}$/i.test(item)).slice(0,5);}
async function remoteError(response:Response){const body=await response.text();const error=new Error(body||`Remote request failed (${response.status}).`) as Error&{status?:number};error.status=response.status;return error;}
function errorResponse(error:unknown){const status=(error as Error&{status?:number}).status??500;const message=error instanceof Error?error.message:"Onboarding failed.";return NextResponse.json({error:message,code:message==="INSUFFICIENT_CREDITS"?"INSUFFICIENT_CREDITS":undefined},{status});}
