import { NextRequest, NextResponse } from "next/server";
import { siteSchema } from "@micirql/schema";
import { buildContentEnrichmentContract, enforceContentEnrichmentIntegrity, groundSiteContent, industryPlannerContext } from "@micirql/design-engine";
import { composeWebsite } from "../../composition-intelligence";
import { inferGenerationQuality } from "../../generation-quality-intelligence";
import { applyComposition } from "../../apply-composition";
import { lockProjectBrief, mergeAiPlanningAdvice } from "../../project-brief-guard";
import { getSupabaseDraft, saveSupabaseDraft } from "../drafts/supabase-store";

function config(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error("Supabase configuration is missing.");return{url,key};}
function auth(request:NextRequest){const authorization=request.headers.get("authorization");if(!authorization?.startsWith("Bearer ")){const error=new Error("AUTH_REQUIRED") as Error&{status?:number};error.status=401;throw error;}return authorization;}
function headers(request:NextRequest){const{key}=config();return{apikey:key,authorization:auth(request),"content-type":"application/json"};}
export async function GET(request:NextRequest){try{const workspaceId=request.nextUrl.searchParams.get("workspaceId")?.trim();const siteId=request.nextUrl.searchParams.get("siteId")?.trim();if(!workspaceId||!siteId)return NextResponse.json({error:"workspaceId and siteId are required"},{status:400});const{url}=config();const query=new URLSearchParams({workspace_id:`eq.${workspaceId}`,site_id:`eq.${siteId}`,select:"*",limit:"1"});const response=await fetch(`${url}/rest/v1/business_onboarding_profiles?${query}`,{headers:headers(request),cache:"no-store"});if(!response.ok)throw await remoteError(response);const rows=await response.json() as unknown[];return NextResponse.json({completed:Boolean((rows[0] as any)?.completed_at),profile:rows[0]??null});}catch(error){return errorResponse(error);}}
export async function POST(request:NextRequest){try{
 const body=await request.json() as Record<string,unknown>;const workspaceId=string(body.workspaceId),siteId=string(body.siteId),businessName=string(body.businessName),industry=string(body.industry);if(!workspaceId||!siteId||!businessName||!industry)return NextResponse.json({error:"workspaceId, siteId, businessName and industry are required"},{status:400});
 const authorization=auth(request);const{url,key}=config();const commonHeaders={apikey:key,authorization,"content-type":"application/json"};const userResponse=await fetch(`${url}/auth/v1/user`,{headers:commonHeaders,cache:"no-store"});if(!userResponse.ok)throw await remoteError(userResponse);const user=await userResponse.json() as{id?:string};if(!user.id)throw new Error("Authenticated user could not be resolved.");
 const services=stringArray(body.services),goals=stringArray(body.goals),styleTags=stringArray(body.styleTags),requiredCapabilities=stringArray(body.requiredCapabilities);const languageValues=stringArray(body.languages),languages=languageValues.length?languageValues:["en"];const subindustry=optionalString(body.subindustry),location=optionalString(body.location),notes=optionalString(body.notes),logoUrl=optionalString(body.logoUrl),brandColors=hexArray(body.brandColors);const lockedBrief=lockProjectBrief({workspaceId,siteId,businessName,industry,subindustry,location,services});const industryContext=industryPlannerContext(lockedBrief.industry,lockedBrief.subindustry??undefined);
 const aiResponse=await fetch(`${url}/functions/v1/ai-plan-site`,{method:"POST",headers:commonHeaders,body:JSON.stringify({workspace_id:lockedBrief.workspaceId,site_id:lockedBrief.siteId,business_name:lockedBrief.businessName,industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,location:lockedBrief.location,services:lockedBrief.services,goals,style_tags:styleTags,required_capabilities:requiredCapabilities,languages,notes,brand_colors:brandColors,industry_context:industryContext})});if(!aiResponse.ok)throw await remoteError(aiResponse);const rawAdvice=await aiResponse.json() as any;const advice=mergeAiPlanningAdvice(lockedBrief,rawAdvice);
 const requestPayload={workspace_id:lockedBrief.workspaceId,site_id:lockedBrief.siteId,industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,style_tags:advice.styleTags,required_capabilities:advice.requiredCapabilities,goals:advice.goals,industry_context:industryContext};const planResponse=await fetch(`${url}/functions/v1/plan-site`,{method:"POST",headers:commonHeaders,body:JSON.stringify(requestPayload)});if(!planResponse.ok)throw await remoteError(planResponse);const plan=await planResponse.json() as{plan_id?:string;blueprint?:unknown};if(!plan.plan_id)throw new Error("Planner did not return a plan ID.");
 const buildResponse=await fetch(`${url}/functions/v1/build-site`,{method:"POST",headers:commonHeaders,body:JSON.stringify({plan_id:plan.plan_id,site_id:lockedBrief.siteId})});if(!buildResponse.ok)throw await remoteError(buildResponse);const buildPayload=await buildResponse.json() as{build?:any};const build=buildPayload.build;const buildId=typeof build==="object"&&build?(build.id??build.build_id??null):null;const brief={businessName:lockedBrief.businessName,industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,location:lockedBrief.location,services:lockedBrief.services,goals,styleTags,requiredCapabilities,languages,notes,logoUrl,brandColors:advice.brandColors,industryContext};
 let content:unknown=null,contentWarning:string|null=null;let contentIntegrity={checked:false,structureIntact:true,appliedFields:0,restoredChanges:[] as string[],corrected:false};let contentGrounding={checked:false,grounded:true,issueCount:0,issues:[] as Array<{pageId:string;sectionId:string;field:string;reason:string}>};try{const builtDraft=await getSupabaseDraft(request,lockedBrief.workspaceId,lockedBrief.siteId);if(!builtDraft)throw new Error("Generated draft could not be loaded for page-specific content enrichment.");const pageContentContract=buildContentEnrichmentContract(builtDraft.snapshot);const contentResponse=await fetch(`${url}/functions/v1/enrich-site-content`,{method:"POST",headers:commonHeaders,body:JSON.stringify({workspace_id:lockedBrief.workspaceId,site_id:lockedBrief.siteId,build_id:buildId,brief,page_content_contract:pageContentContract,content_policy:{mode:"content-only",preserve_page_paths:true,preserve_section_order:true,preserve_component_ids:true,preserve_design_props:true,preserve_media_props:true,preserve_bindings:true,forbid_unsupplied_claims:true}})});if(!contentResponse.ok)throw await remoteError(contentResponse);content=await contentResponse.json();const enrichedDraft=await getSupabaseDraft(request,lockedBrief.workspaceId,lockedBrief.siteId);if(!enrichedDraft)throw new Error("Enriched draft could not be reloaded for integrity verification.");const guarded=enforceContentEnrichmentIntegrity(builtDraft.snapshot,enrichedDraft.snapshot);const grounded=groundSiteContent(guarded.site,{businessName:lockedBrief.businessName,industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,location:lockedBrief.location,services:lockedBrief.services,goals,notes});const validatedSnapshot=siteSchema.parse({...grounded.site,name:lockedBrief.businessName});const corrected=JSON.stringify(validatedSnapshot)!==JSON.stringify(enrichedDraft.snapshot);if(corrected)await saveSupabaseDraft(request,{snapshot:validatedSnapshot,expectedRevision:enrichedDraft.revision});contentIntegrity={checked:true,structureIntact:guarded.structureIntact,appliedFields:guarded.appliedFields,restoredChanges:guarded.restoredChanges,corrected};contentGrounding={checked:true,grounded:grounded.grounded,issueCount:grounded.issues.length,issues:grounded.issues.map(issue=>({pageId:issue.pageId,sectionId:issue.sectionId,field:issue.field,reason:issue.reason}))};}catch(error){contentWarning=error instanceof Error?error.message:"Content enrichment failed.";console.error("MiCirql content enrichment failed; continuing with structural draft.",error);}
 const images={mode:"placeholders",generated:false} as const;const imageWarning:string|null=null;
 const recommendationProfile={industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,services:lockedBrief.services,goals:advice.goals,style_tags:advice.styleTags,required_capabilities:advice.requiredCapabilities};const composition=composeWebsite(recommendationProfile);const quality=inferGenerationQuality(recommendationProfile,composition);let initialPreset:{id:string;name:string;reasons:string[]}|null=null;let initialComposition:{intent:string;sections:Array<{family:string;variant:number;purpose:string;priority:string}>;reasoning:string[]}|null=null;let presetWarning:string|null=null;
 try{const current=await getSupabaseDraft(request,lockedBrief.workspaceId,lockedBrief.siteId);if(!current)throw new Error("Generated draft could not be loaded for composition application.");let nextSnapshot=applyComposition(current.snapshot,composition,quality);nextSnapshot=siteSchema.parse({...nextSnapshot,name:lockedBrief.businessName});const[primary,accent,secondary,surface,border]=advice.brandColors;if(primary||accent||secondary||surface||border){nextSnapshot.theme.brand.colors={...nextSnapshot.theme.brand.colors,...(primary?{primary}:{}),...(accent?{accent}:{}),...(secondary?{secondary,textPrimary:secondary}:{}),...(surface?{surface}:{}),...(border?{border}:{})};nextSnapshot=siteSchema.parse(nextSnapshot);}await saveSupabaseDraft(request,{snapshot:nextSnapshot,expectedRevision:current.revision});initialPreset={id:composition.preset.id,name:composition.preset.name,reasons:composition.reasoning};initialComposition={intent:composition.intent,sections:composition.sections,reasoning:composition.reasoning};}catch(error){presetWarning=error instanceof Error?error.message:"Initial composition could not be applied.";console.error("MiCirql initial composition failed; continuing with generated draft.",error);}
 const profile={workspace_id:lockedBrief.workspaceId,site_id:lockedBrief.siteId,created_by:user.id,business_name:lockedBrief.businessName,industry:lockedBrief.industry,subindustry:lockedBrief.subindustry,location:lockedBrief.location,services:lockedBrief.services,goals,style_tags:styleTags,required_capabilities:requiredCapabilities,languages,notes,logo_url:logoUrl,brand_colors:advice.brandColors,plan_id:plan.plan_id,build_id:buildId,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()};const profileResponse=await fetch(`${url}/rest/v1/business_onboarding_profiles?on_conflict=workspace_id,site_id`,{method:"POST",headers:{...commonHeaders,Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(profile)});if(!profileResponse.ok)throw await remoteError(profileResponse);const savedProfiles=await profileResponse.json() as unknown[];
 return NextResponse.json({ok:true,planId:plan.plan_id,build,blueprint:plan.blueprint,industryContext,planningSource:advice.source,planningProvider:advice.provider??null,planningModel:advice.model??null,planningUsage:advice.usage??null,planningWarning:advice.warning??null,brandPalette:advice.brandColors,content,contentWarning,contentIntegrity,contentGrounding,images,imageWarning,initialPreset,initialComposition,generationQuality:quality,presetWarning,profile:savedProfiles[0]??profile});
}catch(error){return errorResponse(error);}}
function string(value:unknown){return typeof value==="string"?value.trim():"";}function optionalString(value:unknown){const valueString=string(value);return valueString||null;}function stringArray(value:unknown){if(Array.isArray(value))return value.map(string).filter(Boolean);if(typeof value==="string")return value.split(",").map(item=>item.trim()).filter(Boolean);return [];}function hexArray(value:unknown){return stringArray(value).filter(item=>/^#[0-9a-f]{6}$/i.test(item)).slice(0,5);}async function remoteError(response:Response){const body=await response.text();const error=new Error(body||`Remote request failed (${response.status}).`) as Error&{status?:number};error.status=response.status;return error;}function errorResponse(error:unknown){const status=(error as Error&{status?:number}).status??500;return NextResponse.json({error:error instanceof Error?error.message:"Onboarding failed."},{status});}
