import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: "./qa",
  testMatch: [
    "dental-diversity-benchmark.spec.ts",
    "design-diversity-fingerprint.spec.ts",
    "design-theme-family-diversity.spec.ts",
    "design-genome-diversity.spec.ts",
    "review-direction-certification.spec.ts",
    "review-direction-theme-diversity.spec.ts",
    "review-candidate-set-diversity.spec.ts",
    "certified-dental-review-directions.spec.ts",
    "dental-review-ranking.spec.ts",
    "dental-review-server-boundary.spec.ts",
    "dental-review-isolated-viewport.spec.ts",
    "dental-rendered-review-observability.spec.ts",
    "dental-rendered-repair-exact-failures.spec.ts",
    "dental-breakpoint-edge-regression.spec.ts",
    "dental-duplicate-seo-repair.spec.ts",
    "dental-content-quality.spec.ts",
    "content-specialty-rules.spec.ts",
    "dental-architect-content-gate.spec.ts",
    "dental-content-auto-repair.spec.ts",
    "page-media-hero-coordination.spec.ts",
    "hero-coherence-quality.spec.ts",
    "above-fold-composition-quality.spec.ts",
    "healthcare-story-flow-diversity.spec.ts",
    "context-first-onboarding.spec.ts",
    "runtime-provider-resilience.spec.ts",
    "page-architecture-intelligence.spec.ts",
    "exact-asset-placement.spec.ts",
    "native-lead-pipeline.spec.ts",
    "native-leads-inbox.spec.ts",
    "lead-badges-and-notifications.spec.ts",
    "dental-blueprint-application.spec.ts",
    "dental-planner-contract.spec.ts",
    "dental-media-execution.spec.ts",
    "site-visual-quality.spec.ts",
    "asset-perceptual-hash-contract.spec.ts",
    "mobile-navigation-contract.spec.ts",
  ],
  timeout: 30_000,
  fullyParallel: false,
  workers: 1,
  retries: 0,
  reporter: [["list"]],
});