export const LIVE_SITE_STYLES = `
:root{--mi-space-xs:.375rem;--mi-space-sm:.625rem;--mi-space-md:1rem;--mi-space-lg:1.5rem;--mi-space-xl:2.25rem;--mi-content-sm:40rem;--mi-content-md:52rem;--mi-content-lg:72rem;--mi-content-xl:90rem;--mi-focus-ring:0 0 0 3px color-mix(in srgb,var(--mi-color-accent) 28%,transparent)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#fff;color:#111827;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a,button,input,textarea{font:inherit}img{max-width:100%}main{min-height:100svh;background:var(--mi-color-surface);color:var(--mi-color-text);font-family:var(--mi-font-body),system-ui,sans-serif;line-height:var(--mi-body-leading,1.6);overflow-x:clip}
.mi-container{width:min(100% - 2rem,var(--mi-content-lg));margin-inline:auto}.mi-container--sm{max-width:var(--mi-content-sm)}.mi-container--md{max-width:var(--mi-content-md)}.mi-container--xl{max-width:var(--mi-content-xl)}.mi-stack{display:flex;flex-direction:column}.mi-gap--xs{gap:var(--mi-space-xs)}.mi-gap--sm{gap:var(--mi-space-sm)}.mi-gap--md{gap:var(--mi-space-md)}.mi-gap--lg{gap:var(--mi-space-lg)}.mi-gap--xl{gap:var(--mi-space-xl)}.mi-align--center{align-items:center}.mi-type{margin:0;color:var(--mi-color-text)}.mi-type--display,.mi-type--h1,.mi-type--h2,.mi-type--h3{font-family:var(--mi-font-display),system-ui,sans-serif;text-wrap:balance}.mi-type--display{font-size:clamp(2.5rem,9vw,5.5rem);line-height:.98;font-weight:760;letter-spacing:var(--mi-display-tracking,-.04em)}.mi-type--h2{font-size:clamp(1.75rem,5vw,3rem);line-height:1.08;font-weight:720;letter-spacing:-.025em}.mi-type--h3{font-size:clamp(1.25rem,3vw,1.8rem);line-height:1.15;font-weight:700}.mi-type--body{font-size:1rem;line-height:1.65}.mi-type--eyebrow{font-size:.75rem;font-weight:750;letter-spacing:.12em;text-transform:uppercase;color:var(--mi-color-primary)}
.mi-section{padding-block:var(--mi-section-space,clamp(3.5rem,9vw,7rem));background:var(--mi-color-surface);color:var(--mi-color-text)}.mi-section:nth-of-type(even){background:var(--mi-color-surface-elevated)}.mi-section__heading{max-width:44rem}.mi-section__layout{display:grid;gap:var(--mi-space-xl);align-items:center}.mi-section__grid{display:grid;gap:var(--mi-space-md)}.mi-section__media{margin:0;overflow:hidden;border-radius:var(--mi-image-radius,var(--mi-radius-card));box-shadow:var(--mi-shadow-card)}.mi-section__media img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}.mi-section__card{position:relative;min-height:11rem;align-content:start;display:grid;gap:var(--mi-space-sm);padding:var(--mi-space-lg);border:var(--mi-border-width,1px) solid var(--mi-color-border);border-radius:var(--mi-radius-card);background:linear-gradient(145deg,var(--mi-color-surface-elevated),color-mix(in srgb,var(--mi-color-accent) 4%,var(--mi-color-surface)));box-shadow:var(--mi-shadow-card)}.mi-section__card img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:calc(var(--mi-radius-card) * .7)}.mi-section__card-index{color:var(--mi-color-text-muted);font:750 .72rem/1 var(--mi-font-body);letter-spacing:.14em}.mi-section__actions{display:flex;flex-wrap:wrap;gap:var(--mi-space-sm)}.mi-section__action{min-height:44px;display:inline-flex;align-items:center;justify-content:center;padding:.8rem 1rem;border-radius:var(--mi-radius-control);font-weight:700;text-decoration:none}.mi-section__action--primary{background:var(--mi-color-primary);color:var(--mi-color-primary-contrast)}.mi-section__action--secondary{border:1px solid var(--mi-color-border);color:var(--mi-color-text)}
.mi-section--hero{padding-top:clamp(4rem,12vw,9rem)}.mi-section--hero .mi-section__layout{min-height:clamp(30rem,68vh,46rem)}.mi-section--hero .mi-section__media{min-height:18rem;background:linear-gradient(135deg,color-mix(in srgb,var(--mi-color-primary) 88%,#000),color-mix(in srgb,var(--mi-color-accent) 64%,var(--mi-color-secondary)))}.mi-section__media--placeholder{display:grid;place-items:center;min-height:18rem}.mi-section__visual-mark{width:min(62%,16rem);aspect-ratio:1;border:1px solid color-mix(in srgb,var(--mi-color-surface) 45%,transparent);border-radius:38% 62% 52% 48%/42% 44% 56% 58%;transform:rotate(-12deg);background:color-mix(in srgb,var(--mi-color-accent) 34%,transparent)}.mi-section__visual-mark span{display:block;width:42%;aspect-ratio:1;margin:29%;border-radius:50%;background:color-mix(in srgb,var(--mi-color-surface) 72%,transparent)}
.mi-section--navbar{padding-block:0;border-bottom:1px solid var(--mi-color-border);position:relative;z-index:20}.mi-navbar{min-height:4.5rem;display:grid;grid-template-columns:auto minmax(0,1fr) auto;grid-template-areas:"nav brand cta";align-items:center;gap:var(--mi-space-md)}.mi-navbar__brand{grid-area:brand;justify-self:center;min-width:0;color:var(--mi-color-text);font-weight:800;text-decoration:none;overflow-wrap:anywhere}.mi-navbar .mi-nav-menu{grid-area:nav;justify-self:start}.mi-navbar>.mi-section__action{grid-area:cta;max-width:34vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding-inline:.7rem}.mi-navbar a,.mi-footer a{min-height:44px;display:inline-flex;align-items:center}
.mi-nav-menu{position:relative}.mi-nav-menu ul{list-style:none;margin:0;padding:0;display:none}.mi-nav-menu__toggle{min-width:44px;min-height:44px;display:inline-flex;align-items:center;justify-content:center;gap:.5rem;padding:.55rem .7rem;border:1px solid var(--mi-color-border);border-radius:var(--mi-radius-control);background:var(--mi-color-surface);color:var(--mi-color-text);font-weight:700;cursor:pointer}.mi-nav-menu__toggle:focus-visible,.mi-nav-menu a:focus-visible{outline:3px solid var(--mi-color-primary);outline-offset:3px}.mi-nav-menu__icon,.mi-nav-menu__icon::before,.mi-nav-menu__icon::after{display:block;width:1rem;height:2px;border-radius:999px;background:currentColor;content:"";transition:transform .16s ease,top .16s ease,background-color .16s ease}.mi-nav-menu__icon{position:relative}.mi-nav-menu__icon::before,.mi-nav-menu__icon::after{position:absolute;left:0}.mi-nav-menu__icon::before{top:-.32rem}.mi-nav-menu__icon::after{top:.32rem}.mi-nav-menu__toggle.is-open .mi-nav-menu__icon{background:transparent}.mi-nav-menu__toggle.is-open .mi-nav-menu__icon::before{top:0;transform:rotate(45deg)}.mi-nav-menu__toggle.is-open .mi-nav-menu__icon::after{top:0;transform:rotate(-45deg)}.mi-nav-menu ul.is-open{position:absolute;z-index:30;top:calc(100% + .5rem);left:0;display:grid;gap:.2rem;width:min(18rem,calc(100vw - 2rem));padding:.4rem;border:1px solid var(--mi-color-border);border-radius:var(--mi-radius-card);background:var(--mi-color-surface);box-shadow:var(--mi-shadow-card)}.mi-nav-menu a{min-height:44px;display:flex;align-items:center;padding:.55rem .7rem;border-radius:calc(var(--mi-radius-control) * .7);color:inherit;text-decoration:none}.mi-nav-menu a:hover,.mi-nav-menu a:focus-visible{background:var(--mi-color-secondary)}
.mi-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--mi-space-sm)}.mi-gallery__item{margin:0;overflow:hidden;border-radius:var(--mi-radius-card);background:var(--mi-color-secondary)}.mi-gallery__item img{display:block;width:100%;height:100%;aspect-ratio:1;object-fit:cover}.mi-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--mi-space-md);margin:0}.mi-stat{padding:var(--mi-space-md);border:1px solid var(--mi-color-border);border-radius:var(--mi-radius-card);background:var(--mi-color-surface)}.mi-stat dt,.mi-stat span{color:var(--mi-color-text-muted);font-size:.85rem}.mi-stat dd{display:grid;gap:.2rem;margin:.3rem 0 0}.mi-stat strong{font-size:clamp(1.5rem,5vw,2.5rem)}
.mi-section__form{display:grid;gap:var(--mi-space-md)}.mi-section__form label{display:grid;gap:.4rem;font-weight:650}.mi-section__form input,.mi-section__form textarea{width:100%;min-height:44px;border:1px solid var(--mi-color-border);border-radius:var(--mi-radius-control);background:var(--mi-color-surface);color:var(--mi-color-text);padding:.8rem}.mi-section__form textarea{min-height:8rem}.mi-section__form button{min-height:44px;border:0;border-radius:var(--mi-radius-control);background:var(--mi-color-primary);color:var(--mi-color-primary-contrast);font-weight:750}.mi-section--footer{padding-block:clamp(2.5rem,6vw,4.5rem);border-top:1px solid var(--mi-color-border)}.mi-footer{display:grid;gap:var(--mi-space-lg)}.mi-footer__brand{max-width:34rem;display:grid;gap:var(--mi-space-sm)}.mi-footer__brand p,.mi-footer__copyright{margin:0;color:var(--mi-color-text-muted);line-height:1.6}.mi-footer__copyright{margin-top:var(--mi-space-lg);padding-top:var(--mi-space-md);border-top:1px solid var(--mi-color-border);font-size:.85rem}.mi-footer nav{display:flex;flex-wrap:wrap;gap:var(--mi-space-md)}.mi-footer a{color:var(--mi-color-text-muted);padding:.4rem .5rem;text-underline-offset:.2em}
.mi-section-variant--2 .mi-section__heading{max-width:34rem}.mi-section-variant--2 .mi-section__grid{grid-template-columns:1fr}
@media(min-width:34rem){.mi-section-variant--2 .mi-section__grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(min-width:48rem){.mi-container{width:min(100% - 3rem,var(--mi-content-lg))}.mi-section__layout{grid-template-columns:minmax(0,.9fr) minmax(22rem,1.1fr)}.mi-section__grid{grid-template-columns:repeat(3,minmax(0,1fr))}.mi-gallery{grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--mi-space-md)}.mi-stats{grid-template-columns:repeat(4,minmax(0,1fr))}.mi-footer{grid-template-columns:1fr auto}.mi-footer nav{justify-content:flex-end}}
@media(min-width:64rem){.mi-navbar{grid-template-areas:"brand nav cta"}.mi-navbar__brand{justify-self:start}.mi-navbar .mi-nav-menu{justify-self:center}.mi-nav-menu__toggle{display:none}.mi-nav-menu>ul,.mi-nav-menu>ul.is-open{position:static;display:flex;width:auto;padding:0;border:0;background:transparent;box-shadow:none;gap:var(--mi-space-sm)}.mi-nav-menu a{padding:0}}
@media(max-width:47.99rem){.mi-section--hero .mi-section__layout{min-height:0;gap:var(--mi-space-lg)}.mi-section--hero .mi-section__media{min-height:14rem}.mi-section--hero .mi-section__media img{aspect-ratio:16/10}.mi-navbar__brand{max-width:40vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mi-navbar>.mi-section__action{max-width:30vw;font-size:.78rem}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.mi-nav-menu__icon,.mi-nav-menu__icon::before,.mi-nav-menu__icon::after{transition:none}}
`;

export const LIVE_SITE_SCRIPT = `
document.addEventListener("click",function(event){
  var target=event.target instanceof Element?event.target:null;
  var button=target&&target.closest(".mi-nav-menu__toggle");
  document.querySelectorAll(".mi-nav-menu__toggle").forEach(function(candidate){
    var menu=document.getElementById(candidate.getAttribute("aria-controls")||"");
    var isTarget=candidate===button;
    var open=isTarget&&candidate.getAttribute("aria-expanded")!=="true";
    candidate.setAttribute("aria-expanded",String(open));
    candidate.setAttribute("aria-label",(open?"Close":"Open")+" primary navigation");
    candidate.classList.toggle("is-open",open);
    if(menu)menu.classList.toggle("is-open",open);
  });
});
document.addEventListener("keydown",function(event){
  if(event.key!=="Escape")return;
  var button=document.querySelector('.mi-nav-menu__toggle[aria-expanded="true"]');
  if(!(button instanceof HTMLElement))return;
  button.click();button.focus();
});
`;
