export const LIVE_SITE_STYLES = `
:root{--mi-space-xs:.375rem;--mi-space-sm:.625rem;--mi-space-md:1rem;--mi-space-lg:1.5rem;--mi-space-xl:2.25rem;--mi-content-sm:40rem;--mi-content-md:52rem;--mi-content-lg:72rem;--mi-content-xl:90rem;--mi-focus-ring:0 0 0 3px color-mix(in srgb,var(--mi-color-accent) 28%,transparent)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#fff;color:#111827;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a,button,input,textarea{font:inherit}img{max-width:100%}main{min-height:100svh;background:var(--mi-color-surface);color:var(--mi-color-text);font-family:var(--mi-font-body),system-ui,sans-serif;line-height:var(--mi-body-leading,1.6);overflow-x:clip}
.mi-container{width:min(100% - 2rem,var(--mi-content-lg));margin-inline:auto}.mi-container--sm{max-width:var(--mi-content-sm)}.mi-container--md{max-width:var(--mi-content-md)}.mi-container--xl{max-width:var(--mi-content-xl)}.mi-stack{display:flex;flex-direction:column}.mi-gap--xs{gap:var(--mi-space-xs)}.mi-gap--sm{gap:var(--mi-space-sm)}.mi-gap--md{gap:var(--mi-space-md)}.mi-gap--lg{gap:var(--mi-space-lg)}.mi-gap--xl{gap:var(--mi-space-xl)}.mi-align--center{align-items:center}.mi-type{margin:0;color:var(--mi-color-text)}.mi-type--display,.mi-type--h1,.mi-type--h2,.mi-type--h3{font-family:var(--mi-font-display),system-ui,sans-serif;text-wrap:balance}.mi-type--display{font-size:clamp(2.5rem,9vw,5.5rem);line-height:var(--mi-display-leading,.98);font-weight:var(--mi-display-weight,760);letter-spacing:var(--mi-display-tracking,-.04em)}.mi-type--h1{font-size:clamp(2.15rem,7vw,4.2rem);line-height:var(--mi-heading-leading,1.02);font-weight:var(--mi-heading-weight,740);letter-spacing:var(--mi-heading-tracking,-.035em)}.mi-type--h2{font-size:clamp(1.75rem,5vw,3rem);line-height:var(--mi-heading-leading,1.08);font-weight:var(--mi-heading-weight,720);letter-spacing:var(--mi-heading-tracking,-.025em)}.mi-type--h3{font-size:clamp(1.35rem,3vw,2rem);line-height:var(--mi-heading-leading,1.15);font-weight:var(--mi-heading-weight,700);letter-spacing:var(--mi-heading-tracking,-.015em)}.mi-type--body{font-size:1rem;line-height:var(--mi-body-leading,1.65)}.mi-type--eyebrow{font-size:.75rem;font-weight:750;letter-spacing:.12em;text-transform:uppercase;color:var(--mi-color-primary)}
.mi-section{padding-block:var(--mi-section-space,clamp(3.5rem,9vw,7rem));background:var(--mi-color-surface);color:var(--mi-color-text)}.mi-section:nth-of-type(even){background:var(--mi-color-surface-elevated)}.mi-section__heading{max-width:44rem}.mi-section__layout{display:grid;gap:var(--mi-space-xl);align-items:center}.mi-section__grid{display:grid;gap:var(--mi-space-md)}.mi-section__media{margin:0;overflow:hidden;border-radius:var(--mi-image-radius,var(--mi-radius-card));box-shadow:var(--mi-shadow-card)}.mi-section__media img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}.mi-section__card{position:relative;min-height:11rem;align-content:start;display:grid;gap:var(--mi-space-sm);padding:var(--mi-space-lg);border:var(--mi-border-width,1px) solid var(--mi-color-border);border-radius:var(--mi-radius-card);background:linear-gradient(145deg,var(--mi-color-surface-elevated),color-mix(in srgb,var(--mi-color-accent) 4%,var(--mi-color-surface)));box-shadow:var(--mi-shadow-card)}.mi-section__card img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:calc(var(--mi-radius-card) * .7)}.mi-section__card-index{color:var(--mi-color-text-muted);font:750 .72rem/1 var(--mi-font-body);letter-spacing:.14em}.mi-section__actions{display:flex;flex-wrap:wrap;gap:var(--mi-space-sm)}.mi-section__action{min-height:44px;display:inline-flex;align-items:center;justify-content:center;padding:.8rem 1rem;border-radius:var(--mi-radius-control);font-weight:700;text-decoration:none}.mi-section__action--primary{background:var(--mi-color-primary);color:var(--mi-color-primary-contrast)}.mi-section__action--secondary{border:1px solid var(--mi-color-border);color:var(--mi-color-text)}
.mi-section--hero{padding-top:clamp(4rem,12vw,9rem)}.mi-section--hero .mi-section__layout{min-height:clamp(30rem,68vh,46rem)}.mi-section--hero .mi-section__media{min-height:18rem;background:linear-gradient(135deg,color-mix(in srgb,var(--mi-color-primary) 88%,#000),color-mix(in srgb,var(--mi-color-accent) 64%,var(--mi-color-secondary)))}.mi-section__media--placeholder{display:grid;place-items:center;min-height:18rem}.mi-section__visual-mark{width:min(62%,16rem);aspect-ratio:1;border:1px solid color-mix(in srgb,var(--mi-color-surface) 45%,transparent);border-radius:38% 62% 52% 48%/42% 44% 56% 58%;transform:rotate(-12deg);background:color-mix(in srgb,var(--mi-color-accent) 34%,transparent)}.mi-section__visual-mark span{display:block;width:42%;aspect-ratio:1;margin:29%;border-radius:50%;background:color-mix(in srgb,var(--mi-color-surface) 72%,transparent)}
.mi-section--navbar{padding-block:0;border-bottom:1px solid var(--mi-color-border);position:relative;z-index:20}.mi-navbar{min-height:4.5rem;display:grid;grid-template-columns:auto minmax(0,1fr) auto;grid-template-areas:"nav brand cta";align-items:center;gap:var(--mi-space-md)}.mi-navbar__brand{grid-area:brand;justify-self:center;min-width:0;color:var(--mi-color-text);font-weight:800;text-decoration:none;overflow-wrap:anywhere}.mi-navbar .mi-nav-menu{grid-area:nav;justify-self:start}.mi-navbar>.mi-section__action{grid-area:cta;max-width:34vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding-inline:.7rem}.mi-navbar a,.mi-footer a{min-height:44px;display:inline-flex;align-items:center}
.mi-nav-menu{position:relative}.mi-nav-menu ul{list-style:none;margin:0;padding:0;display:none}.mi-nav-menu__toggle{min-width:44px;min-height:44px;display:inline-flex;align-items:center;justify-content:center;gap:.5rem;padding:.55rem .7rem;border:1px solid var(--mi-color-border);border-radius:var(--mi-radius-control);background:var(--mi-color-surface);color:var(--mi-color-text);font-weight:700;cursor:pointer}.mi-nav-menu__toggle:focus-visible,.mi-nav-menu a:focus-visible{outline:3px solid var(--mi-color-primary);outline-offset:3px}.mi-nav-menu__icon,.mi-nav-menu__icon::before,.mi-nav-menu__icon::after{display:block;width:1rem;height:2px;border-radius:999px;background:currentColor;content:"";transition:transform .16s ease,top .16s ease,background-color .16s ease}.mi-nav-menu__icon{position:relative}.mi-nav-menu__icon::before,.mi-nav-menu__icon::after{position:absolute;left:0}.mi-nav-menu__icon::before{top:-.32rem}.mi-nav-menu__icon::after{top:.32rem}.mi-nav-menu__toggle.is-open .mi-nav-menu__icon{background:transparent}.mi-nav-menu__toggle.is-open .mi-nav-menu__icon::before{top:0;transform:rotate(45deg)}.mi-nav-menu__toggle.is-open .mi-nav-menu__icon::after{top:0;transform:rotate(-45deg)}.mi-nav-menu ul.is-open{position:absolute;z-index:30;top:calc(100% + .5rem);left:0;display:grid;gap:.2rem;width:min(18rem,calc(100vw - 2rem));padding:.4rem;border:1px solid var(--mi-color-border);border-radius:var(--mi-radius-card);background:var(--mi-color-surface);box-shadow:var(--mi-shadow-card)}.mi-nav-menu a{min-height:44px;display:flex;align-items:center;padding:.55rem .7rem;border-radius:calc(var(--mi-radius-control) * .7);color:inherit;text-decoration:none}.mi-nav-menu a:hover,.mi-nav-menu a:focus-visible{background:var(--mi-color-secondary)}
.mi-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--mi-space-sm)}.mi-gallery__item{margin:0;overflow:hidden;border-radius:var(--mi-radius-card);background:var(--mi-color-secondary)}.mi-gallery__item img{display:block;width:100%;height:100%;aspect-ratio:1;object-fit:cover}.mi-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--mi-space-md);margin:0}.mi-stat{padding:var(--mi-space-md);border:1px solid var(--mi-color-border);border-radius:var(--mi-radius-card);background:var(--mi-color-surface)}.mi-stat dt,.mi-stat span{color:var(--mi-color-text-muted);font-size:.85rem}.mi-stat dd{display:grid;gap:.2rem;margin:.3rem 0 0}.mi-stat strong{font-size:clamp(1.5rem,5vw,2.5rem)}
.mi-section__form{display:grid;gap:var(--mi-space-md)}.mi-section__form label{display:grid;gap:.4rem;font-weight:650}.mi-section__form input,.mi-section__form textarea{width:100%;min-height:44px;border:1px solid var(--mi-color-border);border-radius:var(--mi-radius-control);background:var(--mi-color-surface);color:var(--mi-color-text);padding:.8rem}.mi-section__form textarea{min-height:8rem}.mi-section__form button{min-height:44px;border:0;border-radius:var(--mi-radius-control);background:var(--mi-color-primary);color:var(--mi-color-primary-contrast);font-weight:750}.mi-section--footer{padding-block:clamp(2.5rem,6vw,4.5rem);border-top:1px solid var(--mi-color-border)}.mi-footer{display:grid;gap:var(--mi-space-lg)}.mi-footer__brand{max-width:34rem;display:grid;gap:var(--mi-space-sm)}.mi-footer__brand p,.mi-footer__copyright{margin:0;color:var(--mi-color-text-muted);line-height:1.6}.mi-footer__copyright{margin-top:var(--mi-space-lg);padding-top:var(--mi-space-md);border-top:1px solid var(--mi-color-border);font-size:.85rem}.mi-footer nav{display:flex;flex-wrap:wrap;gap:var(--mi-space-md)}.mi-footer a{color:var(--mi-color-text-muted);padding:.4rem .5rem;text-underline-offset:.2em}
.mi-section-variant--2 .mi-section__heading{max-width:34rem}.mi-section-variant--2 .mi-section__grid{grid-template-columns:1fr}
@media(min-width:34rem){.mi-section-variant--2 .mi-section__grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(min-width:48rem){.mi-container{width:min(100% - 3rem,var(--mi-content-lg))}.mi-section__layout{grid-template-columns:minmax(0,.9fr) minmax(22rem,1.1fr)}.mi-section__grid{grid-template-columns:repeat(3,minmax(0,1fr))}.mi-gallery{grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--mi-space-md)}.mi-stats{grid-template-columns:repeat(4,minmax(0,1fr))}.mi-footer{grid-template-columns:1fr auto}.mi-footer nav{justify-content:flex-end}}
@media(min-width:64rem){.mi-navbar{grid-template-areas:"brand nav cta"}.mi-navbar__brand{justify-self:start}.mi-navbar .mi-nav-menu{justify-self:center}.mi-nav-menu__toggle{display:none}.mi-nav-menu>ul,.mi-nav-menu>ul.is-open{position:static;display:flex;width:auto;padding:0;border:0;background:transparent;box-shadow:none;gap:var(--mi-space-sm)}.mi-nav-menu a{padding:0}}
@media(max-width:47.99rem){.mi-section--hero .mi-section__layout{min-height:0;gap:var(--mi-space-lg)}.mi-section--hero .mi-section__media{min-height:14rem}.mi-section--hero .mi-section__media img{aspect-ratio:16/10}.mi-navbar__brand{max-width:40vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mi-navbar>.mi-section__action{max-width:30vw;font-size:.78rem}}
.mi-section-theme{position:relative;isolation:isolate}.mi-section-theme .mi-section{position:relative;overflow:clip}.mi-section-theme:nth-child(even) .mi-section{background:var(--mi-color-surface-elevated)}.mi-section-theme .mi-type--eyebrow{width:max-content;max-width:100%;color:var(--mi-color-primary)}.mi-section-theme .mi-section__action{transition:transform var(--mi-motion-fast) ease,box-shadow var(--mi-motion-fast) ease,background-color var(--mi-motion-fast) ease}.mi-section-theme .mi-section__action:hover{transform:translateY(calc(var(--mi-motion-distance,8px) * -.18));box-shadow:var(--mi-shadow-control)}.mi-section-theme .mi-section__composition{position:relative}.mi-section-theme :is(.mi-type--display,.mi-type--h1,.mi-type--h2,.mi-type--h3){max-width:100%;overflow-wrap:break-word}
.mi-section-variant--2[data-section-family=hero] .mi-section__layout{grid-template-columns:minmax(0,1.12fr) minmax(18rem,.88fr)}.mi-section-variant--2[data-section-family=hero] .mi-section__media{order:-1}.mi-section-variant--2[data-section-family=contact] .mi-section__heading{order:2;justify-self:end}.mi-section-variant--2[data-section-family=contact] .mi-section__form,.mi-section-variant--2[data-section-family=contact] .mi-section__layout>div:last-child{order:1}.mi-section-variant--2[data-section-family=footer] .mi-footer{grid-template-columns:1fr}.mi-section-variant--2[data-section-family=footer] .mi-footer nav{justify-content:flex-start}
.mi-section-theme--minimalist .mi-section__card{min-height:0;padding:var(--mi-space-lg) 0;border:0;border-top:1px solid var(--mi-color-border);border-radius:0;background:transparent;box-shadow:none}.mi-section-theme--minimalist .mi-section__grid{column-gap:clamp(1.5rem,4vw,4rem)}.mi-section-theme--minimalist[data-section-family=hero] .mi-section__media{border-radius:0;box-shadow:none}.mi-section-theme--minimalist .mi-section__action--secondary{border-color:transparent;text-decoration:underline;text-underline-offset:.35em}
.mi-section-theme--corporate[data-section-family=hero] .mi-section{background:linear-gradient(90deg,color-mix(in srgb,var(--mi-color-primary) 9%,transparent),transparent 62%),var(--mi-color-surface)}.mi-section-theme--corporate .mi-section__heading{padding-left:var(--mi-space-lg);border-left:4px solid var(--mi-color-primary)}.mi-section-theme--corporate .mi-section__card{border-top:4px solid var(--mi-color-primary);border-radius:calc(var(--mi-radius-card) * .65);box-shadow:none}.mi-section-theme--corporate[data-section-family=process] .mi-stat{border-bottom:4px solid var(--mi-color-accent)}
.mi-section-theme--luxury .mi-type--display,.mi-section-theme--luxury .mi-type--h2{font-weight:420;line-height:.98;letter-spacing:-.045em}.mi-section-theme--luxury .mi-type--eyebrow{letter-spacing:.22em}.mi-section-theme--luxury .mi-section__card{min-height:0;padding-inline:0;border:0;border-top:1px solid color-mix(in srgb,var(--mi-color-accent) 62%,var(--mi-color-border));border-radius:0;background:transparent;box-shadow:none}.mi-section-theme--luxury[data-section-family=hero] .mi-section__media{min-height:clamp(28rem,62vw,44rem)}.mi-section-theme--luxury[data-section-family=hero] .mi-section__media img{height:100%;aspect-ratio:3/4}.mi-section-theme--luxury .mi-section__action--primary{padding-inline:1.5rem;letter-spacing:.06em;text-transform:uppercase}
.mi-section-theme--editorial .mi-section__heading{max-width:50rem}.mi-section-theme--editorial .mi-type--display{font-weight:520;line-height:.94}.mi-section-theme--editorial .mi-section__card{min-height:0;padding:var(--mi-space-lg) 0;border:0;border-top:2px solid var(--mi-color-text);border-radius:0;background:transparent;box-shadow:none}.mi-section-theme--editorial .mi-section__card-index{color:var(--mi-color-accent)}.mi-section-theme--editorial[data-section-family=hero] .mi-section__layout{align-items:end}.mi-section-theme--editorial[data-section-family=hero] .mi-section__media{border-radius:0;box-shadow:none}
.mi-section-theme--glass .mi-section{background:radial-gradient(circle at 88% 12%,color-mix(in srgb,var(--mi-color-accent) 18%,transparent),transparent 34%),radial-gradient(circle at 12% 90%,color-mix(in srgb,var(--mi-color-primary) 12%,transparent),transparent 38%),var(--mi-color-surface)}.mi-section-theme--glass .mi-section__card,.mi-section-theme--glass .mi-stat,.mi-section-theme--glass .mi-section__form{border:1px solid color-mix(in srgb,var(--mi-color-border) 66%,transparent);background:color-mix(in srgb,var(--mi-color-surface-elevated) 78%,transparent);box-shadow:var(--mi-shadow-card);backdrop-filter:blur(var(--mi-backdrop-blur,18px))}.mi-section-theme--glass .mi-section__form{padding:var(--mi-space-lg);border-radius:var(--mi-radius-card)}.mi-section-theme--glass[data-section-family=hero] .mi-section__media{transform:perspective(70rem) rotateY(-3deg) rotateX(1deg)}
.mi-section-theme--maximalist .mi-type--display{font-size:clamp(3rem,8vw,6rem);font-weight:900;line-height:.86;letter-spacing:-.055em}.mi-section-theme--maximalist .mi-section__card{border:2px solid var(--mi-color-text);background:var(--mi-color-surface-elevated);box-shadow:.55rem .55rem 0 color-mix(in srgb,var(--mi-color-accent) 76%,var(--mi-color-text))}.mi-section-theme--maximalist .mi-section__action--primary{border:2px solid var(--mi-color-text);box-shadow:.3rem .3rem 0 var(--mi-color-text)}.mi-section-theme--maximalist[data-section-family=hero] .mi-section{background:linear-gradient(135deg,color-mix(in srgb,var(--mi-color-accent) 24%,transparent) 0 30%,transparent 30% 100%),var(--mi-color-surface)}
.mi-section-theme--organic .mi-section{margin:clamp(.25rem,1vw,.75rem);border-radius:clamp(1.5rem,5vw,4rem)}.mi-section-theme--organic .mi-section__card{border-color:transparent;border-radius:clamp(1.5rem,4vw,3rem)}.mi-section-theme--organic .mi-section__card:nth-child(even){border-radius:3rem 1.25rem 3rem 1.25rem}.mi-section-theme--organic[data-section-family=hero] .mi-section__media,.mi-section-theme--organic[data-section-family=hero] .mi-section__visual-mark{border-radius:44% 56% 38% 62%/54% 40% 60% 46%}.mi-section-theme--organic .mi-section__action--primary{padding-inline:1.4rem;border-radius:999px}
.mi-section-theme--futuristic .mi-section{background:linear-gradient(color-mix(in srgb,var(--mi-color-border) 32%,transparent) 1px,transparent 1px),linear-gradient(90deg,color-mix(in srgb,var(--mi-color-border) 32%,transparent) 1px,transparent 1px),var(--mi-color-surface);background-size:2.25rem 2.25rem}.mi-section-theme--futuristic .mi-type--eyebrow,.mi-section-theme--futuristic .mi-section__card-index{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.mi-section-theme--futuristic .mi-section__card{border-color:color-mix(in srgb,var(--mi-color-accent) 50%,var(--mi-color-border));background:color-mix(in srgb,var(--mi-color-surface-elevated) 92%,transparent);clip-path:polygon(0 0,calc(100% - 1.1rem) 0,100% 1.1rem,100% 100%,0 100%)}.mi-section-theme--futuristic .mi-section__action--primary{box-shadow:0 0 2rem color-mix(in srgb,var(--mi-color-accent) 28%,transparent)}
.mi-section-theme--playful .mi-section{background:radial-gradient(circle,color-mix(in srgb,var(--mi-color-accent) 24%,transparent) 1.5px,transparent 1.6px) 0 0/1.1rem 1.1rem,var(--mi-color-surface)}.mi-section-theme--playful .mi-section__heading{padding:var(--mi-space-lg);border-radius:2rem 2rem .75rem 2rem;background:var(--mi-color-surface-elevated)}.mi-section-theme--playful .mi-section__card{border-width:2px;border-radius:1.5rem 1.5rem .5rem 1.5rem;box-shadow:.35rem .35rem 0 color-mix(in srgb,var(--mi-color-accent) 34%,transparent)}.mi-section-theme--playful .mi-section__card:nth-child(even){margin-top:var(--mi-space-lg);border-radius:.5rem 1.5rem 1.5rem 1.5rem}.mi-section-theme--playful .mi-section__action--primary{border-radius:999px}
.mi-section-theme--cinematic[data-section-family=hero] .mi-section{--mi-color-text:#f8fbfb;--mi-color-text-muted:#d8e3e3;min-height:min(52rem,92svh);padding-block:0;background:#07171c}.mi-section-theme--cinematic[data-section-family=hero] .mi-type--eyebrow{color:#bfeee8}.mi-section-theme--cinematic[data-section-family=hero] .mi-container{width:100%;max-width:none}.mi-section-theme--cinematic[data-section-family=hero] .mi-section__layout{min-height:min(52rem,92svh);display:grid;grid-template-columns:1fr;grid-template-areas:"cinema";align-items:end}.mi-section-theme--cinematic[data-section-family=hero] .mi-section__layout>*{grid-area:cinema}.mi-section-theme--cinematic[data-section-family=hero] .mi-section__layout>div:first-child{z-index:2;width:min(100% - 2rem,72rem);margin-inline:auto;padding-block:clamp(4rem,10vw,8rem)}.mi-section-theme--cinematic[data-section-family=hero] .mi-section__layout>div:first-child>*{max-width:48rem}.mi-section-theme--cinematic[data-section-family=hero] .mi-section__media{position:relative;min-height:inherit;border-radius:0;box-shadow:none}.mi-section-theme--cinematic[data-section-family=hero] .mi-section__media:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgb(3 14 18/.92) 0%,rgb(3 14 18/.52) 56%,rgb(3 14 18/.18) 100%)}.mi-section-theme--cinematic[data-section-family=hero] .mi-section__media img{width:100%;height:100%;min-height:inherit;aspect-ratio:auto}.mi-section-theme--cinematic .mi-type--display{font-size:clamp(3.2rem,10vw,8rem);line-height:.88;text-transform:uppercase}.mi-section-theme--cinematic .mi-section__card{border:0;border-radius:0;background:transparent;box-shadow:none}.mi-section-theme--cinematic[data-section-family=gallery] .mi-gallery__item:first-child{grid-column:span 2;grid-row:span 2}
@media(min-width:48rem){.mi-section-variant--2:not([data-section-family=navbar]):not([data-section-family=hero]):not([data-section-family=contact]):not([data-section-family=footer]) .mi-section__composition{display:grid;grid-template-columns:minmax(14rem,.72fr) minmax(0,1.28fr);column-gap:clamp(2rem,6vw,6rem);align-items:start}.mi-section-variant--2:not([data-section-family=navbar]):not([data-section-family=hero]):not([data-section-family=contact]):not([data-section-family=footer]) .mi-section__heading{grid-column:1;grid-row:1/span 2}.mi-section-variant--2:not([data-section-family=navbar]):not([data-section-family=hero]):not([data-section-family=contact]):not([data-section-family=footer]) .mi-section__grid,.mi-section-variant--2:not([data-section-family=navbar]):not([data-section-family=hero]):not([data-section-family=contact]):not([data-section-family=footer]) .mi-gallery,.mi-section-variant--2:not([data-section-family=navbar]):not([data-section-family=hero]):not([data-section-family=contact]):not([data-section-family=footer]) .mi-stats{grid-column:2;grid-row:1;margin:0}.mi-section-variant--2:not([data-section-family=navbar]):not([data-section-family=hero]):not([data-section-family=contact]):not([data-section-family=footer]) .mi-section__actions{grid-column:2}.mi-section-variant--2[data-section-family=navbar] .mi-navbar{grid-template-areas:"nav cta brand"}.mi-section-variant--2[data-section-family=navbar] .mi-navbar__brand{justify-self:end}.mi-section-theme--editorial[data-section-family=hero] .mi-section__layout,.mi-section-theme--luxury[data-section-family=hero] .mi-section__layout{grid-template-columns:minmax(0,.72fr) minmax(24rem,1.28fr)}.mi-section-theme--playful .mi-section__grid{align-items:start}}
@media(min-width:48rem) and (max-width:71.99rem){.mi-section-theme .mi-type--display{max-width:100%;font-size:clamp(3rem,6vw,4.25rem);overflow-wrap:break-word}.mi-section-variant--2:not([data-section-family=navbar]):not([data-section-family=hero]):not([data-section-family=contact]):not([data-section-family=footer]) .mi-type--h2{font-size:clamp(1.65rem,3.6vw,2.25rem)}}
@media(max-width:47.99rem){.mi-navbar{grid-template-columns:auto minmax(0,1fr);grid-template-areas:"nav brand" "cta cta";row-gap:var(--mi-space-sm);padding-block:var(--mi-space-sm)}.mi-navbar__brand{justify-self:end;max-width:calc(100vw - 6rem)}.mi-navbar>.mi-section__action{width:100%;max-width:none;padding-inline:1rem}.mi-section-variant--2[data-section-family=hero] .mi-section__layout{grid-template-columns:minmax(0,1fr)}.mi-section-variant--2[data-section-family=hero] .mi-section__media,.mi-section-variant--2[data-section-family=contact] .mi-section__heading,.mi-section-variant--2[data-section-family=contact] .mi-section__form,.mi-section-variant--2[data-section-family=contact] .mi-section__layout>div:last-child{order:initial}.mi-section-theme--glass[data-section-family=hero] .mi-section__media{transform:none}.mi-section-theme--playful .mi-section__card:nth-child(even){margin-top:0}.mi-section-theme--cinematic[data-section-family=hero] .mi-section,.mi-section-theme--cinematic[data-section-family=hero] .mi-section__layout{min-height:38rem}.mi-section-theme--cinematic[data-section-family=hero] .mi-section__layout>div:first-child{padding-block:3.5rem}.mi-section-theme--cinematic .mi-type--display{font-size:clamp(2.7rem,14vw,4.8rem)}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.mi-nav-menu__icon,.mi-nav-menu__icon::before,.mi-nav-menu__icon::after,.mi-section-theme .mi-section__action{transition:none}.mi-section-theme .mi-section__action:hover{transform:none}}
`;

export const LIVE_SITE_SCRIPT = `
document.addEventListener("click",function(event){
  var target=event.target instanceof Element?event.target:null;
  var button=target&&target.closest(".mi-nav-menu__toggle");
  document.querySelectorAll(".mi-nav-menu__toggle").forEach(function(candidate){
    var menu=document.getElementById(candidate.getAttribute("aria-controls")||"");
    var isTarget=candidate===button;
    var open=isTarget&&candidate.getAttribute("aria-expanded")!=="true";
    candidate.setAttribute("aria-expanded",String(open));
    candidate.setAttribute("aria-label",(open?"Close":"Open")+" primary navigation");
    candidate.classList.toggle("is-open",open);
    if(menu)menu.classList.toggle("is-open",open);
  });
});
document.addEventListener("keydown",function(event){
  if(event.key!=="Escape")return;
  var button=document.querySelector('.mi-nav-menu__toggle[aria-expanded="true"]');
  if(!(button instanceof HTMLElement))return;
  button.click();button.focus();
});
`;
