import type { CompleteSectionDefinition } from "./schema";

const base = { status: "draft" as const, industries: ["*"], subIndustries: ["*"], capabilities: [], accessibilityNotes: ["semantic landmarks", "keyboard reachable actions", "AA contrast target"], compatibility: { backgrounds: ["light", "dark", "image"], precedingTypes: ["any"] as ["any"], followingTypes: ["any"] as ["any"] } };

export const SECTION_CATALOG: CompleteSectionDefinition[] = [
  { ...base, id:"navbar-quiet-luxury", type:"navbar", name:"Quiet Luxury Navigation", implementationPath:"sections/navbar/quiet-luxury", artDirections:["quiet-luxury","editorial"], moods:["calm","premium"], conversionPurposes:["navigation","primary-cta"], media:{intensity:"none",types:[]}, density:"airy", contentSlots:["brand","links","primaryCta"], mobileBehavior:"compact header with accessible menu and persistent primary action" },
  { ...base, id:"navbar-conversion-clean", type:"navbar", name:"Conversion Clean Navigation", implementationPath:"sections/navbar/conversion-clean", artDirections:["conversion-focused","warm-modern"], moods:["clear","confident"], conversionPurposes:["navigation","primary-cta","call"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["brand","links","phone","primaryCta"], mobileBehavior:"brand plus primary action; secondary links in sheet" },
  { ...base, id:"hero-editorial-split", type:"hero", name:"Editorial Split Hero", implementationPath:"sections/hero/editorial-split", artDirections:["editorial","quiet-luxury"], moods:["premium","human"], conversionPurposes:["positioning","primary-cta"], media:{intensity:"high",types:["portrait","environment"]}, density:"airy", contentSlots:["eyebrow","headline","body","primaryCta","secondaryCta","image"], mobileBehavior:"copy first, editorial image second; preserve generous rhythm" },
  { ...base, id:"hero-cinematic-fullscreen", type:"hero", name:"Cinematic Fullscreen Hero", implementationPath:"sections/hero/cinematic-fullscreen", artDirections:["cinematic","immersive-dark"], moods:["immersive","premium"], conversionPurposes:["positioning","primary-cta"], media:{intensity:"high",types:["environment","video"]}, density:"airy", contentSlots:["headline","body","primaryCta","secondaryCta","media"], mobileBehavior:"crop-safe media with readable overlay and CTA above fold" },
  { ...base, id:"hero-typography-led", type:"hero", name:"Typography Led Hero", implementationPath:"sections/hero/typography-led", artDirections:["typography-led","editorial"], moods:["confident","distinctive"], conversionPurposes:["positioning","primary-cta"], media:{intensity:"low",types:["detail"]}, density:"airy", contentSlots:["eyebrow","headline","body","primaryCta","accentMedia"], mobileBehavior:"fluid headline scale with short measure and immediate CTA" },
  { ...base, id:"hero-conversion-split", type:"hero", name:"Conversion Split Hero", implementationPath:"sections/hero/conversion-split", artDirections:["conversion-focused","warm-modern"], moods:["trustworthy","direct"], conversionPurposes:["primary-cta","secondary-cta","trust"], media:{intensity:"medium",types:["people","environment"]}, density:"balanced", contentSlots:["headline","body","primaryCta","secondaryCta","image","trustLine"], mobileBehavior:"CTA-first stack with media following key value proposition" },
  { ...base, id:"about-editorial-story", type:"about", name:"Editorial Story", implementationPath:"sections/about/editorial-story", artDirections:["editorial","quiet-luxury"], moods:["human","credible"], conversionPurposes:["trust","story"], media:{intensity:"medium",types:["people","environment"]}, density:"airy", contentSlots:["eyebrow","headline","body","image"], mobileBehavior:"story and image alternate without side-by-side compression" },
  { ...base, id:"about-trust-manifesto", type:"about", name:"Trust Manifesto", implementationPath:"sections/about/trust-manifesto", artDirections:["typography-led","warm-modern"], moods:["credible","calm"], conversionPurposes:["trust","positioning"], media:{intensity:"low",types:["detail"]}, density:"airy", contentSlots:["headline","statement","principles"], mobileBehavior:"large statement becomes readable multi-line rhythm" },
  { ...base, id:"services-editorial-index", type:"services", name:"Editorial Service Index", implementationPath:"sections/services/editorial-index", artDirections:["editorial","typography-led"], moods:["premium","clear"], conversionPurposes:["service-discovery"], media:{intensity:"low",types:["detail"]}, density:"balanced", contentSlots:["headline","intro","items"], mobileBehavior:"numbered vertical index with generous tap targets" },
  { ...base, id:"services-visual-stories", type:"services", name:"Visual Service Stories", implementationPath:"sections/services/visual-stories", artDirections:["cinematic","gallery-led"], moods:["immersive","human"], conversionPurposes:["service-discovery","enquiry"], media:{intensity:"high",types:["service","environment"]}, density:"balanced", contentSlots:["headline","items","itemImages","itemCtas"], mobileBehavior:"one story per viewport rhythm; no tiny card grid" },
  { ...base, id:"process-care-journey", type:"process", name:"Care Journey", implementationPath:"sections/process/care-journey", industries:["dental","healthcare"], subIndustries:["*"], artDirections:["warm-modern","editorial","quiet-luxury"], moods:["reassuring","clear"], conversionPurposes:["education","trust"], media:{intensity:"low",types:["detail"]}, density:"balanced", contentSlots:["headline","intro","steps"], capabilities:[], mobileBehavior:"linear narrative; never squeeze steps into horizontal timeline" },
  { ...base, id:"gallery-asymmetric-editorial", type:"gallery", name:"Asymmetric Editorial Gallery", implementationPath:"sections/gallery/asymmetric-editorial", artDirections:["gallery-led","editorial","quiet-luxury"], moods:["premium","immersive"], conversionPurposes:["visual-proof","experience"], media:{intensity:"high",types:["environment","people","detail"]}, density:"airy", contentSlots:["headline","images","captions"], mobileBehavior:"curated staggered sequence with stable aspect ratios" },
  { ...base, id:"faq-calm-disclosure", type:"faq", name:"Calm Disclosure FAQ", implementationPath:"sections/faq/calm-disclosure", artDirections:["quiet-luxury","warm-modern","conversion-focused"], moods:["clear","reassuring"], conversionPurposes:["objection-handling","education"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["headline","intro","questions"], mobileBehavior:"single-column accessible disclosures" },
  { ...base, id:"cta-editorial-band", type:"cta", name:"Editorial CTA Band", implementationPath:"sections/cta/editorial-band", artDirections:["editorial","quiet-luxury","typography-led"], moods:["confident","premium"], conversionPurposes:["primary-cta"], media:{intensity:"low",types:["detail"]}, density:"airy", contentSlots:["headline","body","primaryCta","secondaryCta"], mobileBehavior:"strong headline and full-width primary action" },
  { ...base, id:"cta-human-split", type:"cta", name:"Human Split CTA", implementationPath:"sections/cta/human-split", artDirections:["warm-modern","conversion-focused"], moods:["human","reassuring"], conversionPurposes:["primary-cta","call"], media:{intensity:"medium",types:["people"]}, density:"balanced", contentSlots:["headline","body","image","primaryCta","secondaryCta"], mobileBehavior:"copy before image with immediate action" },
  { ...base, id:"contact-local-conversion", type:"contact", name:"Local Conversion Contact", implementationPath:"sections/contact/local-conversion", artDirections:["conversion-focused","warm-modern"], moods:["clear","trustworthy"], conversionPurposes:["enquiry","call","visit"], media:{intensity:"low",types:["map"]}, density:"balanced", contentSlots:["headline","contactMethods","form","location"], capabilities:["contact","click_to_call","location"], mobileBehavior:"tap-to-call and enquiry action precede form; map last" },
  { ...base, id:"footer-editorial-minimal", type:"footer", name:"Editorial Minimal Footer", implementationPath:"sections/footer/editorial-minimal", artDirections:["editorial","quiet-luxury","typography-led"], moods:["premium","calm"], conversionPurposes:["navigation","contact"], media:{intensity:"none",types:[]}, density:"airy", contentSlots:["brand","statement","links","contact","legal"], mobileBehavior:"stacked groups with generous spacing and no microtext" },
  { ...base, id:"footer-functional-local", type:"footer", name:"Functional Local Footer", implementationPath:"sections/footer/functional-local", artDirections:["warm-modern","conversion-focused"], moods:["clear","credible"], conversionPurposes:["navigation","call","visit"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["brand","links","contact","hours","legal"], capabilities:["click_to_call","location"], mobileBehavior:"contact actions prominent before navigation groups" }
];
