import type { CompleteSectionDefinition } from "./schema";

const base = { status: "draft" as const, industries: ["*"], subIndustries: ["*"], capabilities: [], accessibilityNotes: ["semantic landmarks", "keyboard reachable actions", "AA contrast target"], compatibility: { backgrounds: ["light", "dark", "image"], precedingTypes: ["any"] as ["any"], followingTypes: ["any"] as ["any"] } };

export const EXPANDED_SECTION_CATALOG: CompleteSectionDefinition[] = [
  { ...base, id:"hero-framed-statement", type:"hero", name:"Framed Statement Hero", implementationPath:"sections/hero/framed-statement", artDirections:["framed-minimal","modern-heritage","statement-first","calm-monochrome"], moods:["premium","calm","distinctive"], conversionPurposes:["positioning","primary-cta"], media:{intensity:"low",types:["detail"]}, density:"airy", contentSlots:["eyebrow","headline","body","primaryCta","secondaryCta"], mobileBehavior:"frame becomes edge-to-edge with statement-first hierarchy" },
  { ...base, id:"services-banded-list", type:"services", name:"Banded Service List", implementationPath:"sections/services/banded-list", artDirections:["clinical-refined","precision-grid","direct-modern","framed-minimal"], moods:["clear","precise","premium"], conversionPurposes:["service-discovery","education"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["headline","items"], mobileBehavior:"numbered bands stack with title before description" },
  { ...base, id:"about-split-principles", type:"about", name:"Split Principles About", implementationPath:"sections/about/split-principles", artDirections:["human-narrative","clinical-refined","organic-premium","soft-editorial"], moods:["human","credible","clear"], conversionPurposes:["trust","positioning"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["eyebrow","headline","body","principles"], mobileBehavior:"intro precedes numbered principles in a single reading flow" },
  { ...base, id:"cta-stacked-statement", type:"cta", name:"Stacked Statement CTA", implementationPath:"sections/cta/stacked-statement", artDirections:["statement-first","bold-contrast","layered-depth","modern-heritage"], moods:["confident","premium","distinctive"], conversionPurposes:["primary-cta"], media:{intensity:"none",types:[]}, density:"airy", contentSlots:["eyebrow","headline","body","primaryCta","secondaryCta"], mobileBehavior:"centered statement retains large type with stacked actions" },
];
