import type { CompleteSectionDefinition } from "./schema";

const base = { status: "draft" as const, industries: ["*"], subIndustries: ["*"], capabilities: [], accessibilityNotes: ["semantic landmarks", "keyboard reachable actions", "AA contrast target"], compatibility: { backgrounds: ["light", "dark", "image"], precedingTypes: ["any"] as ["any"], followingTypes: ["any"] as ["any"] } };

export const EXPANDED_SECTION_CATALOG: CompleteSectionDefinition[] = [
  { ...base, id:"hero-framed-statement", type:"hero", name:"Framed Statement Hero", implementationPath:"sections/hero/framed-statement", artDirections:["framed-minimal","modern-heritage","statement-first","calm-monochrome"], moods:["premium","calm","distinctive"], conversionPurposes:["positioning","primary-cta"], media:{intensity:"low",types:["detail"]}, density:"airy", contentSlots:["eyebrow","headline","body","primaryCta","secondaryCta"], mobileBehavior:"frame becomes edge-to-edge with statement-first hierarchy" },
  { ...base, id:"hero-poster-offset", type:"hero", name:"Poster Offset Hero", implementationPath:"sections/hero/poster-offset", artDirections:["bold-contrast","precision-grid","direct-modern","layered-depth"], moods:["graphic","confident","distinctive"], conversionPurposes:["positioning","primary-cta"], media:{intensity:"none",types:[]}, density:"airy", contentSlots:["eyebrow","headline","body","primaryCta","secondaryCta"], mobileBehavior:"poster statement stacks above concise action panel" },
  { ...base, id:"services-banded-list", type:"services", name:"Banded Service List", implementationPath:"sections/services/banded-list", artDirections:["clinical-refined","precision-grid","direct-modern","framed-minimal"], moods:["clear","precise","premium"], conversionPurposes:["service-discovery","education"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["headline","items"], mobileBehavior:"numbered bands stack with title before description" },
  { ...base, id:"services-rail", type:"services", name:"Horizontal Service Rail", implementationPath:"sections/services/rail", artDirections:["bold-contrast","layered-depth","calm-monochrome","organic-premium"], moods:["graphic","structured","premium"], conversionPurposes:["service-discovery","education"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["eyebrow","headline","items"], mobileBehavior:"rail becomes a readable vertical sequence without compressed cards" },
  { ...base, id:"services-featured-offer", type:"services", name:"Featured Offer Services", implementationPath:"sections/services/featured-offer", artDirections:["editorial","quiet-luxury","warm-modern","direct-modern","human-narrative"], moods:["premium","clear","confident"], conversionPurposes:["service-discovery","decision-support"], media:{intensity:"low",types:["detail"]}, density:"balanced", contentSlots:["eyebrow","headline","intro","featuredItem","items"], mobileBehavior:"featured offer leads, supporting offers follow as a vertical editorial sequence" },
  { ...base, id:"about-split-principles", type:"about", name:"Split Principles About", implementationPath:"sections/about/split-principles", artDirections:["human-narrative","clinical-refined","organic-premium","soft-editorial"], moods:["human","credible","clear"], conversionPurposes:["trust","positioning"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["eyebrow","headline","body","principles"], mobileBehavior:"intro precedes numbered principles in a single reading flow" },
  { ...base, id:"about-statement-ledger", type:"about", name:"Statement Ledger About", implementationPath:"sections/about/statement-ledger", artDirections:["precision-grid","bold-contrast","modern-heritage","calm-monochrome"], moods:["disciplined","credible","distinctive"], conversionPurposes:["trust","positioning"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["eyebrow","headline","body","principles"], mobileBehavior:"statement and ledger collapse into one deliberate reading column" },
  { ...base, id:"about-manifesto-columns", type:"about", name:"Manifesto Columns About", implementationPath:"sections/about/manifesto-columns", artDirections:["editorial","statement-first","human-narrative","modern-heritage","soft-editorial"], moods:["credible","human","distinctive"], conversionPurposes:["trust","positioning","story"], media:{intensity:"none",types:[]}, density:"airy", contentSlots:["eyebrow","headline","body","principles"], mobileBehavior:"manifesto statement leads into readable principle columns" },
  { ...base, id:"process-editorial-steps", type:"process", name:"Editorial Process Steps", implementationPath:"sections/process/editorial-steps", artDirections:["editorial","quiet-luxury","precision-grid","warm-modern","direct-modern"], moods:["clear","credible","structured"], conversionPurposes:["education","decision-support","trust"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["eyebrow","headline","intro","steps"], mobileBehavior:"ordered steps remain a single-column reading path with no horizontal timeline dependency" },
  { ...base, id:"cta-stacked-statement", type:"cta", name:"Stacked Statement CTA", implementationPath:"sections/cta/stacked-statement", artDirections:["statement-first","bold-contrast","layered-depth","modern-heritage"], moods:["confident","premium","distinctive"], conversionPurposes:["primary-cta"], media:{intensity:"none",types:[]}, density:"airy", contentSlots:["eyebrow","headline","body","primaryCta","secondaryCta"], mobileBehavior:"centered statement retains large type with stacked actions" },
  { ...base, id:"cta-inverted-marquee", type:"cta", name:"Inverted Marquee CTA", implementationPath:"sections/cta/inverted-marquee", artDirections:["precision-grid","direct-modern","calm-monochrome","organic-premium"], moods:["graphic","confident","premium"], conversionPurposes:["primary-cta"], media:{intensity:"none",types:[]}, density:"airy", contentSlots:["eyebrow","headline","body","primaryCta","secondaryCta"], mobileBehavior:"oversized statement remains dominant while actions stack below" },
  { ...base, id:"cta-decision-panel", type:"cta", name:"Decision Panel CTA", implementationPath:"sections/cta/decision-panel", artDirections:["conversion-focused","warm-modern","framed-minimal","clinical-refined","direct-modern"], moods:["clear","confident","trustworthy"], conversionPurposes:["primary-cta","secondary-cta","decision-support"], media:{intensity:"none",types:[]}, density:"balanced", contentSlots:["eyebrow","headline","body","primaryCta","secondaryCta"], mobileBehavior:"contained decision panel keeps the primary action obvious and the secondary action adjacent" },
];
