import type { PublishableDraft } from "../publish/schema";
import { materializeSiteDraft } from "../materialization/materializer";
import { repairPlanToScopedCss } from "../repair/executor";
import type { CandidateRepairPlan } from "../repair/schema";
import type { RepairAcceptanceResult } from "./evidence";
import type { CandidateCertificationEvidence, CertifiedMaterializedSite, CertifiedWinner } from "./schema";

function validateEvidence(evidence:CandidateCertificationEvidence[]){if(!evidence.length)throw new Error("Certification evidence is required.");const ranks=evidence.map((item)=>item.rank);if(new Set(ranks).size!==ranks.length)throw new Error("Certification evidence contains duplicate ranks.");if(!ranks.includes(1))throw new Error("Certification evidence has no rank-1 candidate.");if(evidence.some((item)=>!Number.isFinite(item.finalScore)))throw new Error("Certification evidence contains an invalid score.");}
export function selectCertifiedWinner(evidence:CandidateCertificationEvidence[]):CertifiedWinner{validateEvidence(evidence);const winner=evidence.find((item)=>item.rank===1);if(!winner)throw new Error("Certified winner is missing.");if(winner.hardFailures.length)throw new Error(`Rank-1 candidate ${winner.candidateId} has hard failures.`);if(!winner.repairAccepted)throw new Error(`Rank-1 candidate ${winner.candidateId} has not passed repair acceptance.`);return{version:"1.0",candidateId:winner.candidateId,rank:1,finalScore:winner.finalScore,certification:{hardFailureCount:0,repairAccepted:true}};}

export function materializeCertifiedWinner({sourceKey,drafts,evidence,repairPlans,repairAcceptance}:{sourceKey:string;drafts:PublishableDraft[];evidence:CandidateCertificationEvidence[];repairPlans?:CandidateRepairPlan[];repairAcceptance?:RepairAcceptanceResult[]}):CertifiedMaterializedSite{
 const winner=selectCertifiedWinner(evidence);const sourceDraft=drafts.find((item)=>item.candidateId===winner.candidateId);if(!sourceDraft)throw new Error(`Certified winner ${winner.candidateId} has no publishable draft.`);if(sourceDraft.readiness!=="ready")throw new Error(`Certified winner ${winner.candidateId} is not publishable.`);
 let draft=sourceDraft;
 if(repairPlans||repairAcceptance){if(!repairPlans||!repairAcceptance)throw new Error("Certified repair persistence requires both repair plan and post-repair acceptance evidence.");const plan=repairPlans.find((item)=>item.candidateId===winner.candidateId);const acceptance=repairAcceptance.find((item)=>item.candidateId===winner.candidateId);if(!plan)throw new Error(`Certified winner ${winner.candidateId} has no bounded repair plan.`);if(!acceptance||acceptance.evidenceState!=="post-repair"||!acceptance.accepted)throw new Error(`Certified winner ${winner.candidateId} lacks accepted post-repair evidence.`);if(plan.requiresRegeneration||plan.allowsArbitraryCodeRewrite!==false)throw new Error(`Certified winner ${winner.candidateId} has an unsafe repair plan.`);const certifiedRepairCss=repairPlanToScopedCss(plan,'main[data-repair-scope="candidate"]');draft={...sourceDraft,certifiedRepairCss};}
 const site=materializeSiteDraft({sourceKey,draft});if(site.source.candidateId!==winner.candidateId)throw new Error("Materialized site candidate does not match certified winner.");if(draft.certifiedRepairCss!==site.snapshot.certifiedRepairCss)throw new Error("Certified repair CSS was not preserved by materialization.");return{version:"1.0",winner,certifiedFingerprint:site.fingerprint,site};
}
